# Generated by Django 3.1.1 on 2020-10-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantdesenv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodatacom',
            name='Estado',
            field=models.ManyToManyField(related_name='TipoDataComEstado', to='instantdesenv.Estado'),
        ),
        migrations.AlterField(
            model_name='palavrachave',
            name='LanguageCode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.languagecode'),
        ),
        migrations.DeleteModel(
            name='TIpoDataComEstado',
        ),
    ]
