# Generated by Django 3.1.1 on 2020-10-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantdesenv', '0002_auto_20201022_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresalinguapais',
            name='TipoProficienciaLingua',
        ),
        migrations.RemoveField(
            model_name='parpartelinguapais',
            name='TipoCargoTrad',
        ),
        migrations.AddField(
            model_name='empresalinguapais',
            name='FormCompl',
            field=models.ManyToManyField(related_name='EmpresaLinguaPaisFormCompl', to='instantdesenv.FormCompl'),
        ),
        migrations.AddField(
            model_name='formacadem',
            name='BancoArquivo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.bancoarquivo'),
        ),
        migrations.AddField(
            model_name='formacadem',
            name='ComprovanteVerificado',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='formcompl',
            name='BancoArquivo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.bancoarquivo'),
        ),
        migrations.AddField(
            model_name='formcompl',
            name='ComprovanteVerificado',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='formcompl',
            name='TipoProficienciaLingua',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoproficiencialingua'),
        ),
        migrations.AddField(
            model_name='partelinguapais',
            name='FormCompl',
            field=models.ManyToManyField(related_name='ParteLinguaPaisFormCompl', to='instantdesenv.FormCompl'),
        ),
        migrations.AddField(
            model_name='partelinguapais',
            name='TipoCargoTrad',
            field=models.ManyToManyField(related_name='ParteLinguaPaisTipoCargoTrad', to='instantdesenv.TipoCargoTrad'),
        ),
        migrations.AddField(
            model_name='partelinguapaistipoproficcateg',
            name='Ordem',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tipocertificacao',
            name='EscalaVisivel',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='tipocertificacao',
            name='TipoFormCompl',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoformcompl'),
        ),
    ]
