# Generated by Django 3.1.2 on 2020-11-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantdesenv', '0003_auto_20201027_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='partelinguapaistipoproficcateg',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AddField(
            model_name='tipofluenciaverb',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AddField(
            model_name='tipoformacadem',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AddField(
            model_name='tipoformcompl',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AddField(
            model_name='tipoproficcateg',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AddField(
            model_name='tipoproficiencialingua',
            name='TipoCtrlQualidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tipoctrlqualidade'),
        ),
        migrations.AlterField(
            model_name='tipodatacom',
            name='AssuntoEMail',
            field=models.TextField(blank=True, default=None, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='tipodatacom',
            name='MsgRedeSocCur',
            field=models.TextField(blank=True, default=None, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='tipodatacom',
            name='MsgSMS',
            field=models.TextField(blank=True, default=None, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='tipodatacom',
            name='Nome',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tiporeligiao',
            name='LanguageCode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.languagecode'),
        ),
    ]
