# Generated by Django 3.1.2 on 2020-11-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instantdesenv', '0004_auto_20201101_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Ordem', models.IntegerField(blank=True, default=None, null=True)),
                ('CodigoDezoitoN', models.IntegerField(blank=True, default=None, null=True)),
                ('LanguageCode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.languagecode')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Ordem', models.IntegerField(blank=True, default=None, null=True)),
                ('CodigoDezoitoN', models.IntegerField(blank=True, default=None, null=True)),
                ('LanguageCode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.languagecode')),
            ],
        ),
        migrations.AddField(
            model_name='parte',
            name='TipoGenero',
            field=models.ManyToManyField(related_name='ParteTipoGenero', to='instantdesenv.TipoGenero'),
        ),
        migrations.AddField(
            model_name='parte',
            name='TipoSexo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instantdesenv.tiposexo'),
        ),
    ]
