"""
Django settings for instant project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r32&-deom%e(@n&hpd0@*_(u@$b0dw4olmzn$bdz6ln1w-opi1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'instantteste.apps.InstantTesteConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django_makemessages_xgettext',
	'rest_framework',
]

REST_FRAMEWORK = {
	# Use Django's standard `django.contrib.auth` permissions,
	# or allow read-only access for unauthenticated users.
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
		'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
	],
	'DEFAULT_RENDERER_CLASSES': [
		'rest_framework.renderers.JSONRenderer',
		'rest_framework.renderers.BrowsableAPIRenderer',
		'rest_framework.renderers.TemplateHTMLRenderer',
	]
}

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'instant.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'instant.wsgi.application'

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
	'default': {
		# 'NAME': 'instant2',
		# 'USER': 'instant2',
		# 'HOST': 'pgsql.instant.simoes.trd.br',
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': 'instantteste',
		'USER': 'postgres',
		'PASSWORD': 'S1m0es',
		'HOST': 'localhost',
		'PORT': '5432',
	}
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
	os.path.join(BASE_DIR, 'locale')
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "teste"), os.path.join(BASE_DIR,'pdf/static/font'),os.path.join(BASE_DIR,'pdf/static/img'),
# ] 

STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.FileSystemFinder',
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media_files'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# # Host for sending e-mail.
# EMAIL_HOST = 'smtpi.kinghost.net'

# # Port for sending e-mail.
# EMAIL_PORT = 465

# # Optional SMTP authentication information for EMAIL_HOST.
# EMAIL_HOST_USER = 'comercial01@simoes.trd.br'
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'simoes.teste0@gmail.com'
EMAIL_HOST_PASSWORD = 'simoes123'

LOGIN_URL = 'tela_proposta'
LOGIN_REDIRECT_URL = 'tela_proposta'
LOGOUT_REDIRECT_URL = 'tela_proposta'

LANGUAGES = (
	('zh-cn', u'中文'),
	('en', u'english'),
	('es', u'español'),
	('de', u'deutsche'),
	('it', u'italiano'),
	('nl', u'nederlands'),
	('fr', u'français'),
	('pt', u'português'),
	('hi', u'हिन्दी'),
	('ja', u'日本語'),
	('ar', u'العربية'),
	('gn', u"avañe'ẽ"),
	('ko', u'한국어'),
	('ru', u'русский'),
	('yor', u'yorùbá'),
	('he', u'עברית'),
	('uk', u'українська'),
	('ng', u'ndonga'),
	('la', u'latina'),
)

# cn -> bandeira da China
# us -> bandeira dos Estados Unidos
# es -> bandeira da Espanha
# de -> bandeira da Alemanha
# it -> bandeira da Itália
# nl -> bandeira da Holanda
# fr -> bandeira da França
# br -> bandeira do Brasil
# in -> bandeira da Índia
# jp -> bandeira do Japão
# sa -> bandeira da Arábia Saudita
# py -> bandeira do Paraguai
# kr -> bandeira da Coréia do Sul
# ru -> bandeira da Rússia
# ng -> bandeira da Nigéria
# il -> bandeira de Israel
# ua -> bandeira da Ucrânia
