from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.utils import timezone, translation


# Create your views here.

class AjaxBusca(View):

	def get(self, request, *args, **kwargs):
		print('args')
		print(args)
		print('kwargs')
		print(kwargs)
		print(request)

		return HttpResponse('result')


class AjaxIdioma(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)

		texto = {
			'zh-cn': """         <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								居民身份证 (中华人民共和国)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'en': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3 tooltiptext" role="alert"> 
								Social Security Number (SSN: USA) / Individual Taxpayer Identification Number (ITIN) / National Insurance Number (NINO: UK) / Tax File Number (TFN: Australia) / Social Insurance Number (SIN: Canada) / NZ GST/IRD Number (GST-IRD: New Zealand) / Tax Identification Number (TIN: Philippines) / Personal Public Service Number (PPS No: Ireland)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'es': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Número de Identificación Fiscal (NIF: España) / Número de Identidad de Extranjero (NIE: España) / Código Único de Identificación Tributaria (CUIT: Argentina) / Rol Único Tributario (RUT: Chile) / Registro Único Tributario (RUT: Uruguay) / Registro Federal de Contribuyentes (RFC: México) / Número de Identificación Tributaria (NIT: Colombia, Bolivia, El Salvador y Guatemala) / Registro de Informacion Fiscal (RIF: Venezuela) / Registro Único de Contribuyentes (RUC: Nicaragua, Panamá, Paraguay, Perú y Ecuador) / Registro Tributario Nacional (RTN: Honduras) / Registro Nacional del Contribuyente (RNC: República Dominicana) / Cédula Persona Física (Costa Rica)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'de': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Steuer-Identifikationsnummer (NIE: Deutschland) / Umsatzsteuer-Identifikationsnummer (USt-IdNr.: Deutschland) / Mehrwertsteuernummer (MWST-Nr.: Schweiz) / Umsatzsteuer-Identifikationsnummer (UID: Österreich) / Nationalregisternummer (Belgien) / Momsregistreringsnummer (SE-Nr.-CVR: Dänemark) / Sozialversicherungsnummer (Schweiz)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'it': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Codice Fiscale (Italia) / Mehrwertsteuernummer (MWST/TVA/IVA: Svizzera) / Codice operatore economico (COE: San Marino)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'nl': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Burgerservicenummer (BSN: Nederland) / Rijksregisternummer (RNN: België)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'fr': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Numéro de Sécurité Sociale (NIR: France et Monaco) / Numéro d'Assurance Sociale (NAS: Canada) / Numéro de Registre National (N.N.: Belgique) / Numéro de TVA (TVA: Suisse) / Numéro d'identification à la taxe sur la valeur ajoutée (IBLC Nr.: Luxembourg)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'pt': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Cadastro de Pessoas Físicas (CPF: Brasil) / Número de Identificação Fiscal (NIF: Portugal) / Número de Identificação Fiscal (NIF: Angola)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'hi': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								आधार (भारत)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'ja': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								個人番号 (日本)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'ar': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								(رقم الهوية (السعودية / (رقم الهوية (الإمارات العربية المتحدة
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'gn': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Registro Único de Contribuyentes (RUC: Tetã Paraguái) / Cadastro de Pessoas Físicas (CPF: Pindoráma) / Número de Identificación Tributaria (NIT: Tetã Vorívia) / Código Único de Identificación Tributaria (CUIT: Tetã Argentína)								
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'ko': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								주민등록번호 (대한민국)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'ru': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Страховой номер индивидуального лицевого счёта (СНИЛС: Росси́я)				
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'yor': """           <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								National Identification Number (NIN: Nàìjíríà)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'he': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								(ת ז:יִשְׂרָאֵל) תעודת זהות
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'uk': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Ідентифікаційний номер платника податків (ІПН, Україна)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'ng': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">

								<br>

								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
			'la': """            <div id = 'caixa_info' class="alert alert-warning alert-dismissible fade show m-3" role="alert">
								Codice Fiscale (Vaticanæ)
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>""",
		}

		if kwargs['langcode'] in texto.keys():

			alerta = texto[kwargs['langcode']]
		else:

			alerta = texto['en']

		print(request)

		return HttpResponse(alerta)


class AjaxIdiomaCadastro(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)

		cadastro = {
			'zh-cn': [
				'名和中间名（无缩写）',
				'姓',
				'生日dd / mm / yyyy ',
				'数',
				'电邮',
				'密码'
			],
			'en': [
				'First name and middle name (without abbreviation)',
				'Surname',
				'Date of birth dd / mm / yyyy ',
				'Number',
				'Email',
				'Password',
			],
			'es': [
				'Nombre y segundo nombre (sin abreviatura)',
				'Apellido',
				'Fecha de nacimiento dd / mm / aaaa ',
				'Número',
				'Correo electrónico',
				'Contraseña',
			],
			'de': [
				'Vor- und Nachname (ohne Abkürzung)',
				'Nachname',
				'Geburtsdatum TT / MM / JJJJ ',
				'Nummer',
				'E-Mail',
				'Passwort',
			],
			'it': [
				'Nome e secondo nome (senza abbreviazione)',
				'Cognome',
				'Data di nascita gg / mm / aaaa ',
				'Numero',
				'e-mail',
				'Password',
			],
			'nl': [
				'Voornaam en middelste naam (zonder afkorting)',
				'Achternaam',
				'Geboortedatum dd / mm / jjjj ',
				'Aantal',
				'E-mail',
				'Wachtwoord',
			],
			'fr': [
				'Prénom et deuxième prénom (sans abréviation)',
				'Nom de famille',
				'Date de naissance jj / mm / aaaa ',
				'Nombre',
				'Courriel',
				'Mot de passe',
			],
			'pt': [
				'Primeiro nome e nome do meio (sem abreviatura)',
				'Sobrenome',
				'Data de nascimento dd/mm/aaaa',
				'Número',
				'Email',
				'Senha',
			],
			'hi': [
				'पहला नाम और मध्य नाम (संक्षिप्त नाम के बिना)',
				'उपनाम',
				'जन्म तिथि dd / mm / yyyy ',
				'संख्या',
				'ईमेल',
				'पासवर्ड',
			],
			'ja': [
				'名とミドルネーム（略称なし）',
				'姓',
				'生年月日dd / mm / yyyy ',
				'数',
				'電子メール',
				'パスワード',
			],
			'ar': [
				'الاسم الأول والاسم الأوسط (بدون اختصار)',
				'لقب',
				'تاريخ الميلاد dd / mm / yyyy ',
				'رقم',
				'البريد الإلكتروني',
				'كلمة المرور',
			],
			'gn': [
				"téra ha mokõiha-2-/aravo'ive téra ( abreviaturaỹre )",
				'terajoapy',
				"ára Ñesẽ mba'e dd/mm/aaaa",
				'papaha',
				'pareha electrónico',
				'contraseña',
			],
			'ko': [
				'이름과 중간 이름 (약어 제외)',
				'성',
				'생년월일 dd / mm / yyyy ',
				'번호',
				'이메일',
				'비밀번호',
			],
			'ru': [
				'Имя и отчество (без сокращения)',
				'Фамилия',
				'Дата рождения дд / мм / гггг ',
				'число',
				'по электронной почте',
				'пароль',
			],
			'yor': [
				'Orukọ akọkọ ati orukọ aarin (laisi abbreviation)',
				'Orukọ idile',
				'Ọjọ ibi dd / mm / yyyy ',
				'Nọmba',
				'Imeeli',
				'Ọrọ aṣina',
			],
			'he': [
				'שם פרטי ושם אמצעי (ללא קיצור)',
				'שם משפחה',
				'תאריך לידה dd / mm / yyyy ',
				'מספר',
				'דוא"ל',
				'סיסמא',
			],
			'uk': [
				"Ім'я та прізвище (без абревіатури)",
				'Прізвище',
				'Дата народження дд / мм / рр. ',
				'число',
				'Електронна пошта',
				'Пароль',
			],
			'la': [
				'Nomen et praenomen medio (sine abbreviationem)',
				'surname',
				'Date nativitatis dd / mm / aaaa ',
				'Numerus',
				'inscriptio',
				'password',
			],
		}

		if kwargs['langcode'] in cadastro.keys():
			sep = '///'
			alerta = sep.join(cadastro[kwargs['langcode']])
		else:
			sep = '///'
			alerta = sep.join('en')

		print(request)

		return HttpResponse(alerta)


class AjaxIdiomaCPF(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)
		op = '<option value="{dado}">{dado}</option>'
		alerta = ''
		texto = {
			'zh-cn': [
				"居民身份证 (中华人民共和国)",
				"其他"
			],
			'en': [
				"SSN (USA)",
				"ITIN (USA)",
				"NINO (UK)",
				"TFN (Australia)",
				"SIN (Canada)",
				"GST-IRD (New Zealand)",
				"TIN (Philippines)",
				"PPS No (Ireland)",
				"Other"
			],
			'es': [
				"NIF (España)",
				"NIE (España)",
				"CUIT (Argentina)",
				"RUT (Chile)",
				"RUT (Uruguay)",
				"RFC (México)",
				"NIT (Colombia)",
				"NIT (Bolivia)",
				"NIT (Salvador)",
				"NIT (Guatemala)",
				"RIF (Venezuela)",
				"RUC (Nicaragua)",
				"RUC (Panamá)",
				"RUC (Paraguay)",
				"RUC (Perú)",
				"RUC (Ecuador)",
				"RTN (Honduras)",
				"RNC (República Dominicana)",
				"Cédula Persona Física (Costa Rica)",
				"Otro"
			],
			'de': [
				"NIE (Deutschland)",
				"Sozialversicherungsnummer (Schweiz)",
				"UID (Österreich)",
				"Nationalregisternummer (Belgien)",
				"SE-Nr.-CVR (Dänemark)",
				"Andere"
			],
			'it': [
				"Codice Fiscale (Italia)",
				"MWST/TVA/IVA (Svizzera)",
				"COE (San Marino)",
				"Altro"
			],
			'nl': [
				"BSN (Nederland)",
				"RNN (België)",
				"Andere"
			],
			'fr': [
				"NIR (France)",
				"NIR (Monaco)",
				"NAS (Canada)",
				"N.N. (Belgique)",
				"TVA (Suisse)",
				"IBLC Nr. (Luxembourg)",
				"Autre"
			],
			'pt': [
				"CPF (Brasil)",
				"NIF (Portugal)",
				"NIF (Angola)",
				"Outro"
			],
			'hi': [
				"आधार (भारत)",
				"अन्य"
			],
			'ja': [
				"個人番号",
				"その他の"
			],
			'ar': [
				"(رقم الهوية (السعودية",
				"(رقم الهوية (الإمارات العربية المتحدة",
				"آخر"
			],
			'gn': [
				"RUC (Tetã Paraguái)",
				"CPF (Pindoráma)",
				"NIT (Tetã Vorívia)",
				"CUIT (Tetã Argentína)",
				"ambue"
			],
			'ko': [
				"주민등록번호",
				"다른"
			],
			'ru': [
				"СНИЛС (Росси́я)",
				"Другой"
			],
			'yor': [
				"NIN (Nàìjíríà)",
				"Omiiran"
			],
			'he': [
				"יִשְׂרָאֵל) ת ז)",
				"אחר"
			],
			'uk': [
				"ІПН",
				"Інший"
			],
			'ng': [],
			'la': [
				"Codice Fiscale (Vaticanæ)",
				"alius"
			],
		}

		if kwargs['langcode'] in texto.keys():
			for dado in texto[kwargs['langcode']]:
				alerta = alerta + op.format(dado=dado)
		else:
			for dado in texto['en']:
				alerta = alerta + op.format(dado=dado)

		print(request)

		return HttpResponse(alerta)


class AjaLinkDownload(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)

		download = {
			'zh-cn': 'http://jieshao.simoes.trd.br',
			'en': 'http://presentation.simoes.trd.br',
			'es': 'http://presentacion.simoes.trd.br',
			'de': 'http://prasentation.simoes.trd.br',
			'it': 'http://presentazione.simoes.trd.br',
			'nl': 'http://presentatie.simoes.trd.br',
			'fr': 'http://lettrepresentation.simoes.trd.br',
			'pt': 'http://apresentacao.simoes.trd.br',
			'hi': 'http://prastuteekaran.simoes.trd.br',
			'ja': 'http://purezenteshon.simoes.trd.br',
			'ar': 'http://eard.simoes.trd.br',
			'gn': 'http://mbojexauka.simoes.trd.br',
			'ko': 'http://pyosi.simoes.trd.br',
			'ru': 'http://prezentatsiya.simoes.trd.br',
			'yor': 'http://igbejade.simoes.trd.br',
			'he': 'http://vidua.simoes.trd.br',
			'uk': 'http://prezentatsiynyylyst.simoes.trd.br',
			'la': 'http://praesentationem.simoes.trd.br',
		}

		if kwargs['langcode'] in download.keys():
			link = download[kwargs['langcode']]
		else:
			link = download['en']

		print(request)

		return HttpResponse(link)


class AjaxIdiomaCode(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)
		# <img class="bandeiras m-1" src="data:image/png;base64, 0000"  alt="{Dado_NomeOriginal}">

		# queryset = models.BancoImagem.objects.all()
		# print(queryset)

		op = '''<div class = "country_code">
				<label for="{Dado_NomeOriginal_id}" class = "my-auto py-1 input_codigo">
				<img class="bandeiras m-1" src="data:image/png;base64, {img_texto}"  alt="{Dado_NomeOriginal}">
				{Dado_NomeOriginal}		
				</label>
				<input value="{Dado_NomeOriginal}" type="radio" id="{Dado_NomeOriginal_id}" name="codigo" class="">
				</div>'''
		alerta = ''

		texto = {
			'zh-cn': [
				'中国+86',
				'丹麦+45',
				'乌克兰+380',
				'乌拉圭+598',
				'以色列+972',
				'俄罗斯+7',
				'加拿大+1',
				'卢森堡+352',
				'印度+91',
				'危地马拉+502',
				'厄瓜多尔+593',
				'哥伦比亚+57',
				'哥斯达黎加+506',
				'圣马力诺+378',
				'墨西哥+52',
				'多米尼加共和国+1809',
				'奥地利+43',
				'委内瑞拉+58',
				'安哥拉+244',
				'尼加拉瓜+505',
				'尼日利亚+234',
				'巴拉圭+595',
				'巴拿马+507',
				'巴西+55',
				'德国+49',
				'意大利+39',
				'摩纳哥+377',
				'新西兰+64',
				'日本+81',
				'智利+56',
				'梵蒂冈+39',
				'比利时+32',
				'沙特阿拉伯+966',
				'法国+33',
				'洪都拉斯+504',
				'澳大利亚+61',
				'爱尔兰+353',
				'玻利维亚+591',
				'瑞士+41',
				'秘鲁+51',
				'美国+1',
				'英国+44',
				'荷兰+31',
				'菲律宾+63',
				'萨尔瓦多+503',
				'葡萄牙+351',
				'西班牙+34',
				'阿拉伯联合酋长国+971',
				'阿根廷+54',
				'韩国+82',
			],
			'en': [
				'Angola +244',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgium +32',
				'Bolivia +591',
				'Brazil +55',
				'Canada +1',
				'Chile +56',
				'China +86',
				'Colombia +57',
				'Costa Rica +506',
				'Denmark +45',
				'Dominican Republic +1809',
				'Ecuador +593',
				'El Salvador +503',
				'France +33',
				'Germany +49',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Ireland +353',
				'Israel +972',
				'Italy +39',
				'Japan +81',
				'Luxembourg +352',
				'Mexico +52',
				'Monaco +377',
				'Netherlands +31',
				'New Zealand +64',
				'Nicaragua +505',
				'Nigeria +234',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Philippines +63',
				'Portugal +351',
				'Russia +7',
				'San Marino +378',
				'Saudi Arabia +966',
				'South Korea +82',
				'Spain +34',
				'Switzerland +41',
				'Ukraine +380',
				'United Arab Emirates +971',
				'United Kingdom +44',
				'United States +1',
				'Uruguay +598',
				'Vatican +39',
				'Venezuela +58',
			],
			'es': [
				'Alemania +49',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Bélgica +32',
				'Bolivia +591',
				'Brasil +55',
				'Canadá +1',
				'Chile +56',
				'China +86',
				'Colombia +57',
				'Corea del Sur +82',
				'Costa Rica +506',
				'Dinamarca +45',
				'Ecuador +593',
				'El Salvador +503',
				'Emiratos Árabes Unidos +971',
				'España +34',
				'Estados Unidos +1',
				'Filipinas +63',
				'Francia +33',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Irlanda +353',
				'Israel +972',
				'Italia +39',
				'Japón +81',
				'Luxemburgo +352',
				'México +52',
				'Mónaco +377',
				'Nicaragua +505',
				'Nigeria +234',
				'Nueva Zelanda +64',
				'Países Bajos +31',
				'Panamá +507',
				'Paraguay +595',
				'Perú +51',
				'Portugal +351',
				'Reino Unido +44',
				'República Dominicana +1809',
				'Rusia +7',
				'San Marino +378',
				'Suiza +41',
				'Ucrania +380',
				'Uruguay +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'de': [
				'Angola +244',
				'Argentinien +54',
				'Australien +61',
				'Belgien +32',
				'Bolivien +591',
				'Brasilien +55',
				'Chile +56',
				'China +86',
				'Costa Rica +506',
				'Dänemark +45',
				'Deutschland +49',
				'Dominikanische Republik +1809',
				'Ecuador +593',
				'El Salvador +503',
				'Frankreich +33',
				'Guatemala +502',
				'Honduras +504',
				'Indien +91',
				'Irland +353',
				'Israel +972',
				'Italien +39',
				'Japan +81',
				'Kanada +1',
				'Kolumbien +57',
				'Luxemburg +352',
				'Mexiko +52',
				'Monaco +377',
				'Neuseeland +64',
				'Nicaragua +505',
				'Niederlande +31',
				'Nigeria +234',
				'Österreich +43',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Philippinen +63',
				'Portugal +351',
				'Russland +7',
				'San Marino +378',
				'Saudi-Arabien +966',
				'Schweiz +41',
				'Spanien +34',
				'Südkorea +82',
				'Ukraine +380',
				'Uruguay +598',
				'Vatikan +39',
				'Venezuela +58',
				'Vereinigte Arabische Emirate +971',
				'Vereinigte Staaten +1',
				'Vereinigtes Königreich +44',
			],
			'it': [
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgio +32',
				'Bolivia +591',
				'Brasile +55',
				'Canada +1',
				'Cile +56',
				'Cina +86',
				'Colombia +57',
				'Corea del Sud +82',
				'Costa Rica +506',
				'Danimarca +45',
				'Ecuador +593',
				'El Salvador +503',
				'Emirati Arabi Uniti +971',
				'Filippine +63',
				'Francia +33',
				'Germania +49',
				'Giappone +81',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Irlanda +353',
				'Israele +972',
				'Italia +39',
				'Lussemburgo +352',
				'Messico +52',
				'Monaco +377',
				'Nicaragua +505',
				'Nigeria +234',
				'Nuova Zelanda +64',
				'Paesi Bassi +31',
				'Panama +507',
				'Paraguay +595',
				'Perù +51',
				'Portogallo +351',
				'Regno Unito +44',
				'Repubblica Dominicana +1809',
				'Russia +7',
				'San Marino +378',
				'Spagna +34',
				'Stati Uniti +1',
				'Svizzera +41',
				'Ucraina +380',
				'Uruguay +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'nl': [
				'Angola +244',
				'Argentinië +54',
				'Australië +61',
				'België +32',
				'Bolivia +591',
				'Brazilië +55',
				'Canada +1',
				'Chili +56',
				'China +86',
				'Colombia +57',
				'Costa Rica +506',
				'Denemarken +45',
				'Dominicaanse Republiek +1809',
				'Duitsland +49',
				'Ecuador +593',
				'El Salvador +503',
				'Filipijnen +63',
				'Frankrijk +33',
				'Guatemala +502',
				'Honduras +504',
				'Ierland +353',
				'India +91',
				'Israël +972',
				'Italië +39',
				'Japan +81',
				'Luxemburg +352',
				'Mexico +52',
				'Monaco +377',
				'Nederland +31',
				'Nicaragua +505',
				'Nieuw-Zeeland +64',
				'Nigeria + 234',
				'Oekraïne +380',
				'Oostenrijk +43',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Portugal +351',
				'Rusland +7',
				'San Marino +378',
				'Saoedi-Arabië +966',
				'Spanje +34',
				'Uruguay +598',
				'Vaticaan +39',
				'Venezuela +58',
				'Verenigd Koninkrijk +44',
				'Verenigde Arabische Emiraten +971',
				'Verenigde Staten +1',
				'Zuid-Korea +82',
				'Zwitserland +41',
			],
			'fr': [
				'Allemagne +49',
				'Angola +244',
				'Arabie saoudite +966',
				'Argentine +54',
				'Australie +61',
				'Autriche +43',
				'Belgique +32',
				'Bolivie +591',
				'Brésil +55',
				'Canada +1',
				'Chili +56',
				'Chine +86',
				'Colombie +57',
				'Corée du Sud +82',
				'Costa Rica +506',
				'Danemark +45',
				'El Salvador +503',
				'Émirats Arabes Unis +971',
				'Équateur +593',
				'Espagne +34',
				'États-Unis +1',
				'France +33',
				'Guatemala +502',
				'Honduras +504',
				'Inde +91',
				'Irlande +353',
				'Israël +972',
				'Italie +39',
				'Japon +81',
				'Luxembourg +352',
				'Mexique +52',
				'Monaco +377',
				'Nicaragua +505',
				'Nigéria +234',
				'Nouvelle-Zélande +64',
				'Panama +507',
				'Paraguay +595',
				'Pays-Bas +31',
				'Pérou +51',
				'Philippines +63',
				'Portugal +351',
				'République Dominicaine +1809',
				'Royaume-Uni +44',
				'Russie +7',
				'Saint-Marin +378',
				'Suisse +41',
				'Ukraine +380',
				'Uruguay +598',
				'Vatican +39',
				'Venezuela +58',
			],
			'pt': [
				'Alemanha +49',
				'Angola +244',
				'Arábia Saudita +966',
				'Argentina +54',
				'Austrália +61',
				'Áustria +43',
				'Bélgica +32',
				'Bolívia +591',
				'Brasil +55',
				'Canadá +1',
				'Chile +56',
				'China +86',
				'Colômbia +57',
				'Coreia do Sul +82',
				'Costa Rica +506',
				'Dinamarca +45',
				'El Salvador +503',
				'Emirados Árabes Unidos +971',
				'Equador +593',
				'Espanha +34',
				'Estados Unidos +1',
				'Filipinas +63',
				'França +33',
				'Guatemala +502',
				'Holanda +31',
				'Honduras +504',
				'Índia +91',
				'Irlanda +353',
				'Israel +972',
				'Itália +39',
				'Japão +81',
				'Luxemburgo +352',
				'México +52',
				'Mônaco +377',
				'Nicarágua +505',
				'Nigéria +234',
				'Nova Zelândia +64',
				'Panamá +507',
				'Paraguai +595',
				'Peru +51',
				'Portugal +351',
				'Reino Unido +44',
				'República Dominicana +1809',
				'Rússia +7',
				'São Marino +378',
				'Suiça +41',
				'Ucrânia +380',
				'Uruguai +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'hi': [
				'अंगोला 16:4',
				'अर्जेंटीना +54',
				'अल साल्वाडोर +503',
				'आयरलैंड +353',
				'इक्वाडोर +593',
				'इज़राइल +972',
				'इटली +39',
				'उरुग्वे +598',
				'ऑस्ट्रिया +43',
				'ऑस्ट्रेलिया +61',
				'कनाडा +1',
				'कोलंबिया +57',
				'कोस्टा रिका +506',
				'ग्वाटेमाला +502',
				'चिली +56',
				'चीन +86',
				'जर्मनी +49',
				'जापान +81',
				'डेनमार्क +45',
				'डोमिनिकन गणराज्य +1809',
				'दक्षिण कोरिया +82',
				'नाइजीरिया 13:4',
				'निकारागुआ +505',
				'नीदरलैंड +31',
				'न्यूजीलैंड +64',
				'पनामा +507',
				'पराग्वे +595',
				'पुर्तगाल +351',
				'पेरू +51',
				'फिलीपींस +63',
				'फ्रांस +33',
				'बेल्जियम +32',
				'बोलीविया +591',
				'ब्राजील +55',
				'भारत +91',
				'मेक्सिको +52',
				'मोनाको +377',
				'यूक्रेन +380',
				'यूनाइटेड किंगडम +44',
				'रूस +7',
				'लक्समबर्ग +352',
				'वेटिकन +39',
				'वेनेजुएला +58',
				'संयुक्त अरब अमीरात +971',
				'संयुक्त राज्य अमेरिका +1',
				'सऊदी अरब +966',
				'सैन मैरिनो +378',
				'स्पेन +34',
				'स्विट्जरलैंड +41',
				'होंडुरास +504',
			],
			'ja': [
				'アイルランド+353',
				'アメリカ合衆国+1',
				'アラブ首長国連邦+971',
				'アルゼンチン+54',
				'アンゴラ+244',
				'イギリス+44',
				'イスラエル+972',
				'イタリア+39',
				'インド+91',
				'ウクライナ+380',
				'ウルグアイ+598',
				'エクアドル+593',
				'エルサルバドル+503',
				'オーストラリア+61',
				'オーストリア+43',
				'オランダ+31',
				'カナダ+1',
				'グアテマラ+502',
				'コスタリカ+506',
				'コロンビア+57',
				'サウジアラビア+966',
				'サンマリノ+378',
				'スイス+41',
				'スペイン+34',
				'チリ+56',
				'デンマーク+45',
				'ドイツ+49',
				'ドミニカ共和国+1809',
				'ナイジェリア+234',
				'ニカラグア+505',
				'ニュージーランド+64',
				'バチカン+39',
				'パナマ+507',
				'パラグアイ+595',
				'フィリピン+63',
				'ブラジル+55',
				'フランス+33',
				'ベネズエラ+58',
				'ペルー+51',
				'ベルギー+32',
				'ボリビア+591',
				'ポルトガル+351',
				'ホンジュラス+504',
				'メキシコ+52',
				'モナコ+377',
				'ルクセンブルク+352',
				'ロシア+7',
				'中国+86',
				'日本+81',
				'韓国+82',
			],
			'ar': [
				'الإمارات العربية المتحدة +971',
				'الأرجنتين +54',
				'البرازيل +55',
				'البرتغال +351',
				'الدنمارك +45',
				'السلفادور +503',
				'الصين +86',
				'الفاتيكان +39',
				'الفلبين +63',
				'المكسيك +52',
				'المملكة العربية السعودية +966',
				'المملكة المتحدة +44',
				'النمسا +43',
				'الهند +91',
				'الولايات المتحدة +1',
				'اليابان +81',
				'إسبانيا +34',
				'إسرائيل +972',
				'إكوادور +593',
				'إيطاليا +39',
				'أستراليا +61',
				'ألمانيا +49',
				'أنغولا +244',
				'أوروغواي +598',
				'أوكرانيا +380',
				'أيرلندا +353',
				'باراغواي +595',
				'بلجيكا +32',
				'بنما +507',
				'بوليفيا +591',
				'بيرو +51',
				'تشيلي +56',
				'جمهورية الدومينيكان +1809',
				'روسيا +7',
				'سان مارينو +378',
				'سويسرا +41',
				'غواتيمالا +502',
				'فرنسا +33',
				'فنزويلا +58',
				'كندا +1',
				'كوريا الجنوبية +82',
				'كوستاريكا +506',
				'كولومبيا +57',
				'لوكسمبورج +352',
				'موناكو +377',
				'نيجيريا +234',
				'نيكاراغوا +505',
				'نيوزيلندا +64',
				'هندوراس +504',
				'هولندا +31',
			],
			'gn': [
				'Alemaña +49',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Austráliape +61',
				'Áustriape +43',
				'Bélgicape +32',
				'Volivia +591',
				'Pindorama +55',
				'Kanatã +1',
				'Chile +56',
				'Tetã China +86',
				'Kolómbia +57',
				'Yvykorea +82',
				'Costa Rícagui +506',
				'Ndinamayka +45',
				'Ekuator +593',
				'Pe Salvador +503',
				'Aravia Emiryvy Joaju +971',
				'España +34',
				'Estados Unídospe káda +1',
				'Filipinas +63',
				'Hyãsia +33',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Ilandia +353',
				'Israel +972',
				'Italia +39',
				'Hapõ +81',
				'Luxemburgo +352',
				'Méjiko +52',
				'Múnich +377',
				'Ojeproivírõ +505',
				'Nigériape +234',
				'Nueva Zelandaygua +64',
				'Holandaygua +31',
				'Panamáme oĩ +507',
				'Paraguái +595',
				'Perũ +51',
				'Poytuga +351',
				'Tavetã Joaju +44',
				'República Dominicanagua +1809',
				'Rrusia +7',
				'San Marino +378',
				'Suízape +41',
				'Ukyaña +380',
				'Uruguái +598',
				'Vaticano +39',
				'Venesuéla +58',
			],
			'ko': [
				'과테말라 +502',
				'나이지리아 +234',
				'네덜란드 +31',
				'뉴질랜드 +64',
				'니카라과 +505',
				'대한민국 +82',
				'덴마크 +45',
				'도미니카 공화국 +1809',
				'독일 +49',
				'러시아 +7',
				'룩셈부르크 +352',
				'멕시코 +52',
				'모나코 +377',
				'미국 +1',
				'바티칸 +39',
				'베네수엘라 +58',
				'벨기에 +32',
				'볼리비아 +591',
				'브라질 +55',
				'사우디 아라비아 +966',
				'산 마리노 +378',
				'스위스 +41',
				'스페인 +34',
				'아랍 에미리트 +971',
				'아르헨티나 +54',
				'아일랜드 +353',
				'앙골라 +244',
				'에콰도르 +593',
				'엘살바도르 +503',
				'영국 +44',
				'오스트레일리아 +61',
				'오스트리아 +43',
				'온두라스 +504',
				'우루과이 +598',
				'우크라이나 +380',
				'이스라엘 +972',
				'이탈리아 +39',
				'인도 +91',
				'일본 +81',
				'중국 +86',
				'칠레 +56',
				'캐나다 +1',
				'코스타리카 +506',
				'콜롬비아 +57',
				'파나마 +507',
				'파라과이 +595',
				'페루 +51',
				'포르투갈 +351',
				'프랑스 +33',
				'필리핀 +63',
			],
			'ru': [
				'Австралия +61',
				'Австрия +43',
				'Ангола +244',
				'Аргентина +54',
				'Бельгия +32',
				'Боливия +591',
				'Бразилия +55',
				'Ватикан +39',
				'Великобритания +44',
				'Венесуэла +58',
				'Гватемала +502',
				'Германия +49',
				'Гондурас +504',
				'Дания +45',
				'Доминиканская Республика +1809',
				'Израиль +972',
				'Индия +91',
				'Ирландия +353',
				'Испания +34',
				'Италия +39',
				'Канада +1',
				'Китай +86',
				'Колумбия +57',
				'Коста-Рика +506',
				'Люксембург +352',
				'Мексика +52',
				'Монако +377',
				'Нигерия +234',
				'Нидерланды +31',
				'Никарагуа +505',
				'Новая Зеландия +64',
				'Объединенные Арабские Эмираты +971',
				'Панама +507',
				'Парагвай +595',
				'Перу +51',
				'Португалия +351',
				'Россия +7',
				'Сальвадор +503',
				'Сан-Марино +378',
				'Саудовская Аравия +966',
				'США +1',
				'Украина +380',
				'Уругвай +598',
				'Филиппины +63',
				'Франция +33',
				'Чили +56',
				'Швейцария +41',
				'Эквадор +593',
				'Южная Корея +82',
				'Япония +81',
			],
			'yor': [
				'Amẹrika +1',
				'Angola +244',
				'Apapọ Arab Emirates +971',
				'Ará Argentina +54',
				'Australia +61',
				'Austria +43',
				'Bẹljiọmu +32',
				'Bolivia +591',
				'Chile +56',
				'Costa Rica +506',
				'Ecuador +593',
				'Egeskov +45',
				'El Salvador +503',
				'Faranse +33',
				'Fiorino +31',
				'Guatemala +502',
				'Guusu koria +82',
				'Honduras +504',
				'Ilu Bánándì +55',
				'Ilu Columbia +57',
				'Ilu Italia +39',
				'Ilu Pọtugali +351',
				'India +91',
				'Ireland +353',
				'Israeli +972',
				'Japan +81',
				'Jẹmánì +49',
				'Kanada +1',
				'Luxembourg +352',
				'Meksiko +52',
				'Monaco +377',
				'Nàìjíríà +234',
				'New Zealand +64',
				'Nicaragua +505',
				'Orilẹ-ede Dominican +1809',
				'Panama +507',
				'Paraguay +595',
				'Perú +51',
				'Philippines +63',
				'Russia +7',
				'Ṣaina +86',
				'San Marino +378',
				'Saudi Arabia +966',
				'Sibeeni +34',
				'Siwitsalandi +41',
				'United Kingdom +44',
				'Urugue +598',
				'Vatican +39',
				'Venezuela +58',
				'Yukirenia +380',
			],
			'he': [
				'אוסטריה +43',
				'אוסטרליה +61',
				'אוקראינה +380',
				'אורוגוואי +598',
				'איחוד האמירויות הערביות +971',
				'איטליה +39',
				'אירלנד +353',
				'אל סלבדור +503',
				'אנגולה +244',
				'אקוודור +593',
				'ארגנטינה +54',
				'ארצות הברית +1',
				'בוליביה +591',
				'בלגיה +32',
				'ברזיל +55',
				'בריטניה +44',
				'גואטמלה +502',
				'גרמניה +49',
				'דנמרק +45',
				'דרום קוריאה +82',
				'הודו +91',
				'הוותיקן +39',
				'הולנד +31',
				'הונדורס +504',
				'הפיליפינים +63',
				'הרפובליקה הדומיניקנית +1809',
				'ונצואלה +58',
				'יפן +81',
				'ישראל +972',
				'לוקסמבורג +352',
				'מונקו +377',
				'מקסיקו +52',
				'ניגריה +234',
				'ניו זילנד +64',
				'ניקרגואה +505',
				'סין +86',
				'סן מרינו +378',
				'סעודיה +966',
				'ספרד +34',
				'פורטוגל +351',
				'פנמה +507',
				'פרגוואי +595',
				'פרו +51',
				"צ'ילה +56",
				'צרפת +33',
				'קולומביה +57',
				'קוסטה ריקה +506',
				'קנדה +1',
				'רוסיה +7',
				'שוויץ +41',
			],
			'uk': [
				'Австралія +61',
				'Австрія +43',
				'Ангола +244',
				'Аргентина +54',
				'Бельгія +32',
				'Болівія +591',
				'Бразилія +55',
				'Ватикан +39',
				'Великобританія +44',
				'Венесуела +58',
				'Гватемала +502',
				'Гондурас +504',
				'Данія +45',
				'Домініканська Республіка +1809',
				'Еквадор +593',
				'Ізраїль +972',
				'Індія +91',
				'Ірландія +353',
				'Іспанія +34',
				'Італія +39',
				'Канада +1',
				'Китай +86',
				'Колумбія +57',
				'Коста-Ріка +506',
				'Люксембург +352',
				'Мексика +52',
				'Монако +377',
				'Нігерія +234',
				'Нідерланди +31',
				'Нікарагуа +505',
				'Німеччина +49',
				'Нова Зеландія +64',
				"Об'єднані Арабські Емірати +971",
				'Панама +507',
				'Парагвай +595',
				'Перу +51',
				'Південна Корея +82',
				'Португалія +351',
				'Росія +7',
				'Сальвадор +503',
				'Сан-Марино +378',
				'Саудівська Аравія +966',
				'США +1',
				'Україна +380',
				'Уругвай +598',
				'Філіппіни +63',
				'Франція +33',
				'Чилі +56',
				'Швейцарія +41',
				'Японія +81',
			],
			'la': [
				'Aequatoria +593',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgium +32',
				'Bolivia +591',
				'Brasilia +55',
				'Britanniarum regnum +44',
				'Canada +1',
				'Chile +56',
				'Civitates Foederatae +1',
				'Colombia +57',
				'Costa Rica +506',
				'Dania +45',
				'Emiratus Arabici Coniuncti +971',
				'Gallia +33',
				'Germania +49',
				'Helvetia +41',
				'Hibernia +353',
				'Hispaniam +34',
				'Honduria +504',
				'Iaponia +81',
				'India +91',
				'Israel +972',
				'Italia +39',
				'Luxemburgum +352',
				'Mexico +52',
				'Monoecus +377',
				'Netherlands +31',
				'Nicaragua +505',
				'Nigeria +234',
				'Nova Zelandia +64',
				'Panama +507',
				'Paraquaria +595',
				'Peruvia +51',
				'Philippinae +63',
				'Portugal +351',
				'Res publica Coreana +82',
				'Res publica Dominiciana +1809',
				'Res publica Sancti Marini +378',
				'Russia +7',
				'Salvatoria +503',
				'Sinis +86',
				'Ucraina +380',
				'Uraquaria +598',
				'Vat +39',
				'Venetiola +58',
				'Vivamus +502',
			],
		}

		if kwargs['langcode'] in texto.keys():
			for dado in texto[kwargs['langcode']]:
				temp = op.format(
					Dado_NomeOriginal=dado,
					Dado_NomeOriginal_id=dado.replace(' ', ''),
					img_texto='texto'
				)
				alerta = alerta + temp
		else:
			for dado in texto['en']:
				alerta = alerta + op.format(Dado_NomeOriginal=dado)

		# print(alerta)

		return HttpResponse(alerta)

class AjaxCodigoPais(View):

	def get(self, request, *args, **kwargs):

		print('args')
		print(args)
		print('kwargs')
		print(kwargs)
		op = '<option value="{dado}">{dado}</option>'
		# <img class="bandeiras m-1" src="data:image/png;base64, 0000"  alt="{Dado_NomeOriginal}">onclick="TrocaCodigo()
		alerta = []

		cur_language = translation.get_language()
		print(cur_language)

		# queryset = models.BancoImagem.objects.all().values()
		# print(queryset)

		texto = {
			'zh-cn': [
				'中国+86',
				'丹麦+45',
				'乌克兰+380',
				'乌拉圭+598',
				'以色列+972',
				'俄罗斯+7',
				'加拿大+1',
				'卢森堡+352',
				'印度+91',
				'危地马拉+502',
				'厄瓜多尔+593',
				'哥伦比亚+57',
				'哥斯达黎加+506',
				'圣马力诺+378',
				'墨西哥+52',
				'多米尼加共和国+1809',
				'奥地利+43',
				'委内瑞拉+58',
				'安哥拉+244',
				'尼加拉瓜+505',
				'尼日利亚+234',
				'巴拉圭+595',
				'巴拿马+507',
				'巴西+55',
				'德国+49',
				'意大利+39',
				'摩纳哥+377',
				'新西兰+64',
				'日本+81',
				'智利+56',
				'梵蒂冈+39',
				'比利时+32',
				'沙特阿拉伯+966',
				'法国+33',
				'洪都拉斯+504',
				'澳大利亚+61',
				'爱尔兰+353',
				'玻利维亚+591',
				'瑞士+41',
				'秘鲁+51',
				'美国+1',
				'英国+44',
				'荷兰+31',
				'菲律宾+63',
				'萨尔瓦多+503',
				'葡萄牙+351',
				'西班牙+34',
				'阿拉伯联合酋长国+971',
				'阿根廷+54',
				'韩国+82',
			],
			'en': [
				'Angola +244',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgium +32',
				'Bolivia +591',
				'Brazil +55',
				'Canada +1',
				'Chile +56',
				'China +86',
				'Colombia +57',
				'Costa Rica +506',
				'Denmark +45',
				'Dominican Republic +1809',
				'Ecuador +593',
				'El Salvador +503',
				'France +33',
				'Germany +49',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Ireland +353',
				'Israel +972',
				'Italy +39',
				'Japan +81',
				'Luxembourg +352',
				'Mexico +52',
				'Monaco +377',
				'Netherlands +31',
				'New Zealand +64',
				'Nicaragua +505',
				'Nigeria +234',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Philippines +63',
				'Portugal +351',
				'Russia +7',
				'San Marino +378',
				'Saudi Arabia +966',
				'South Korea +82',
				'Spain +34',
				'Switzerland +41',
				'Ukraine +380',
				'United Arab Emirates +971',
				'United Kingdom +44',
				'United States +1',
				'Uruguay +598',
				'Vatican +39',
				'Venezuela +58',
			],
			'es': [
				'Alemania +49',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Bélgica +32',
				'Bolivia +591',
				'Brasil +55',
				'Canadá +1',
				'Chile +56',
				'China +86',
				'Colombia +57',
				'Corea del Sur +82',
				'Costa Rica +506',
				'Dinamarca +45',
				'Ecuador +593',
				'El Salvador +503',
				'Emiratos Árabes Unidos +971',
				'España +34',
				'Estados Unidos +1',
				'Filipinas +63',
				'Francia +33',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Irlanda +353',
				'Israel +972',
				'Italia +39',
				'Japón +81',
				'Luxemburgo +352',
				'México +52',
				'Mónaco +377',
				'Nicaragua +505',
				'Nigeria +234',
				'Nueva Zelanda +64',
				'Países Bajos +31',
				'Panamá +507',
				'Paraguay +595',
				'Perú +51',
				'Portugal +351',
				'Reino Unido +44',
				'República Dominicana +1809',
				'Rusia +7',
				'San Marino +378',
				'Suiza +41',
				'Ucrania +380',
				'Uruguay +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'de': [
				'Angola +244',
				'Argentinien +54',
				'Australien +61',
				'Belgien +32',
				'Bolivien +591',
				'Brasilien +55',
				'Chile +56',
				'China +86',
				'Costa Rica +506',
				'Dänemark +45',
				'Deutschland +49',
				'Dominikanische Republik +1809',
				'Ecuador +593',
				'El Salvador +503',
				'Frankreich +33',
				'Guatemala +502',
				'Honduras +504',
				'Indien +91',
				'Irland +353',
				'Israel +972',
				'Italien +39',
				'Japan +81',
				'Kanada +1',
				'Kolumbien +57',
				'Luxemburg +352',
				'Mexiko +52',
				'Monaco +377',
				'Neuseeland +64',
				'Nicaragua +505',
				'Niederlande +31',
				'Nigeria +234',
				'Österreich +43',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Philippinen +63',
				'Portugal +351',
				'Russland +7',
				'San Marino +378',
				'Saudi-Arabien +966',
				'Schweiz +41',
				'Spanien +34',
				'Südkorea +82',
				'Ukraine +380',
				'Uruguay +598',
				'Vatikan +39',
				'Venezuela +58',
				'Vereinigte Arabische Emirate +971',
				'Vereinigte Staaten +1',
				'Vereinigtes Königreich +44',
			],
			'it': [
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgio +32',
				'Bolivia +591',
				'Brasile +55',
				'Canada +1',
				'Cile +56',
				'Cina +86',
				'Colombia +57',
				'Corea del Sud +82',
				'Costa Rica +506',
				'Danimarca +45',
				'Ecuador +593',
				'El Salvador +503',
				'Emirati Arabi Uniti +971',
				'Filippine +63',
				'Francia +33',
				'Germania +49',
				'Giappone +81',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Irlanda +353',
				'Israele +972',
				'Italia +39',
				'Lussemburgo +352',
				'Messico +52',
				'Monaco +377',
				'Nicaragua +505',
				'Nigeria +234',
				'Nuova Zelanda +64',
				'Paesi Bassi +31',
				'Panama +507',
				'Paraguay +595',
				'Perù +51',
				'Portogallo +351',
				'Regno Unito +44',
				'Repubblica Dominicana +1809',
				'Russia +7',
				'San Marino +378',
				'Spagna +34',
				'Stati Uniti +1',
				'Svizzera +41',
				'Ucraina +380',
				'Uruguay +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'nl': [
				'Angola +244',
				'Argentinië +54',
				'Australië +61',
				'België +32',
				'Bolivia +591',
				'Brazilië +55',
				'Canada +1',
				'Chili +56',
				'China +86',
				'Colombia +57',
				'Costa Rica +506',
				'Denemarken +45',
				'Dominicaanse Republiek +1809',
				'Duitsland +49',
				'Ecuador +593',
				'El Salvador +503',
				'Filipijnen +63',
				'Frankrijk +33',
				'Guatemala +502',
				'Honduras +504',
				'Ierland +353',
				'India +91',
				'Israël +972',
				'Italië +39',
				'Japan +81',
				'Luxemburg +352',
				'Mexico +52',
				'Monaco +377',
				'Nederland +31',
				'Nicaragua +505',
				'Nieuw-Zeeland +64',
				'Nigeria + 234',
				'Oekraïne +380',
				'Oostenrijk +43',
				'Panama +507',
				'Paraguay +595',
				'Peru +51',
				'Portugal +351',
				'Rusland +7',
				'San Marino +378',
				'Saoedi-Arabië +966',
				'Spanje +34',
				'Uruguay +598',
				'Vaticaan +39',
				'Venezuela +58',
				'Verenigd Koninkrijk +44',
				'Verenigde Arabische Emiraten +971',
				'Verenigde Staten +1',
				'Zuid-Korea +82',
				'Zwitserland +41',
			],
			'fr': [
				'Allemagne +49',
				'Angola +244',
				'Arabie saoudite +966',
				'Argentine +54',
				'Australie +61',
				'Autriche +43',
				'Belgique +32',
				'Bolivie +591',
				'Brésil +55',
				'Canada +1',
				'Chili +56',
				'Chine +86',
				'Colombie +57',
				'Corée du Sud +82',
				'Costa Rica +506',
				'Danemark +45',
				'El Salvador +503',
				'Émirats Arabes Unis +971',
				'Équateur +593',
				'Espagne +34',
				'États-Unis +1',
				'France +33',
				'Guatemala +502',
				'Honduras +504',
				'Inde +91',
				'Irlande +353',
				'Israël +972',
				'Italie +39',
				'Japon +81',
				'Luxembourg +352',
				'Mexique +52',
				'Monaco +377',
				'Nicaragua +505',
				'Nigéria +234',
				'Nouvelle-Zélande +64',
				'Panama +507',
				'Paraguay +595',
				'Pays-Bas +31',
				'Pérou +51',
				'Philippines +63',
				'Portugal +351',
				'République Dominicaine +1809',
				'Royaume-Uni +44',
				'Russie +7',
				'Saint-Marin +378',
				'Suisse +41',
				'Ukraine +380',
				'Uruguay +598',
				'Vatican +39',
				'Venezuela +58',
			],
			'pt': [
				'Alemanha +49',
				'Angola +244',
				'Arábia Saudita +966',
				'Argentina +54',
				'Austrália +61',
				'Áustria +43',
				'Bélgica +32',
				'Bolívia +591',
				'Brasil +55',
				'Canadá +1',
				'Chile +56',
				'China +86',
				'Colômbia +57',
				'Coreia do Sul +82',
				'Costa Rica +506',
				'Dinamarca +45',
				'El Salvador +503',
				'Emirados Árabes Unidos +971',
				'Equador +593',
				'Espanha +34',
				'Estados Unidos +1',
				'Filipinas +63',
				'França +33',
				'Guatemala +502',
				'Holanda +31',
				'Honduras +504',
				'Índia +91',
				'Irlanda +353',
				'Israel +972',
				'Itália +39',
				'Japão +81',
				'Luxemburgo +352',
				'México +52',
				'Mônaco +377',
				'Nicarágua +505',
				'Nigéria +234',
				'Nova Zelândia +64',
				'Panamá +507',
				'Paraguai +595',
				'Peru +51',
				'Portugal +351',
				'Reino Unido +44',
				'República Dominicana +1809',
				'Rússia +7',
				'São Marino +378',
				'Suiça +41',
				'Ucrânia +380',
				'Uruguai +598',
				'Vaticano +39',
				'Venezuela +58',
			],
			'hi': [
				'अंगोला 16:4',
				'अर्जेंटीना +54',
				'अल साल्वाडोर +503',
				'आयरलैंड +353',
				'इक्वाडोर +593',
				'इज़राइल +972',
				'इटली +39',
				'उरुग्वे +598',
				'ऑस्ट्रिया +43',
				'ऑस्ट्रेलिया +61',
				'कनाडा +1',
				'कोलंबिया +57',
				'कोस्टा रिका +506',
				'ग्वाटेमाला +502',
				'चिली +56',
				'चीन +86',
				'जर्मनी +49',
				'जापान +81',
				'डेनमार्क +45',
				'डोमिनिकन गणराज्य +1809',
				'दक्षिण कोरिया +82',
				'नाइजीरिया 13:4',
				'निकारागुआ +505',
				'नीदरलैंड +31',
				'न्यूजीलैंड +64',
				'पनामा +507',
				'पराग्वे +595',
				'पुर्तगाल +351',
				'पेरू +51',
				'फिलीपींस +63',
				'फ्रांस +33',
				'बेल्जियम +32',
				'बोलीविया +591',
				'ब्राजील +55',
				'भारत +91',
				'मेक्सिको +52',
				'मोनाको +377',
				'यूक्रेन +380',
				'यूनाइटेड किंगडम +44',
				'रूस +7',
				'लक्समबर्ग +352',
				'वेटिकन +39',
				'वेनेजुएला +58',
				'संयुक्त अरब अमीरात +971',
				'संयुक्त राज्य अमेरिका +1',
				'सऊदी अरब +966',
				'सैन मैरिनो +378',
				'स्पेन +34',
				'स्विट्जरलैंड +41',
				'होंडुरास +504',
			],
			'ja': [
				'アイルランド+353',
				'アメリカ合衆国+1',
				'アラブ首長国連邦+971',
				'アルゼンチン+54',
				'アンゴラ+244',
				'イギリス+44',
				'イスラエル+972',
				'イタリア+39',
				'インド+91',
				'ウクライナ+380',
				'ウルグアイ+598',
				'エクアドル+593',
				'エルサルバドル+503',
				'オーストラリア+61',
				'オーストリア+43',
				'オランダ+31',
				'カナダ+1',
				'グアテマラ+502',
				'コスタリカ+506',
				'コロンビア+57',
				'サウジアラビア+966',
				'サンマリノ+378',
				'スイス+41',
				'スペイン+34',
				'チリ+56',
				'デンマーク+45',
				'ドイツ+49',
				'ドミニカ共和国+1809',
				'ナイジェリア+234',
				'ニカラグア+505',
				'ニュージーランド+64',
				'バチカン+39',
				'パナマ+507',
				'パラグアイ+595',
				'フィリピン+63',
				'ブラジル+55',
				'フランス+33',
				'ベネズエラ+58',
				'ペルー+51',
				'ベルギー+32',
				'ボリビア+591',
				'ポルトガル+351',
				'ホンジュラス+504',
				'メキシコ+52',
				'モナコ+377',
				'ルクセンブルク+352',
				'ロシア+7',
				'中国+86',
				'日本+81',
				'韓国+82',
			],
			'ar': [
				'الإمارات العربية المتحدة +971',
				'الأرجنتين +54',
				'البرازيل +55',
				'البرتغال +351',
				'الدنمارك +45',
				'السلفادور +503',
				'الصين +86',
				'الفاتيكان +39',
				'الفلبين +63',
				'المكسيك +52',
				'المملكة العربية السعودية +966',
				'المملكة المتحدة +44',
				'النمسا +43',
				'الهند +91',
				'الولايات المتحدة +1',
				'اليابان +81',
				'إسبانيا +34',
				'إسرائيل +972',
				'إكوادور +593',
				'إيطاليا +39',
				'أستراليا +61',
				'ألمانيا +49',
				'أنغولا +244',
				'أوروغواي +598',
				'أوكرانيا +380',
				'أيرلندا +353',
				'باراغواي +595',
				'بلجيكا +32',
				'بنما +507',
				'بوليفيا +591',
				'بيرو +51',
				'تشيلي +56',
				'جمهورية الدومينيكان +1809',
				'روسيا +7',
				'سان مارينو +378',
				'سويسرا +41',
				'غواتيمالا +502',
				'فرنسا +33',
				'فنزويلا +58',
				'كندا +1',
				'كوريا الجنوبية +82',
				'كوستاريكا +506',
				'كولومبيا +57',
				'لوكسمبورج +352',
				'موناكو +377',
				'نيجيريا +234',
				'نيكاراغوا +505',
				'نيوزيلندا +64',
				'هندوراس +504',
				'هولندا +31',
			],
			'gn': [
				'Alemaña +49',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Austráliape +61',
				'Áustriape +43',
				'Bélgicape +32',
				'Volivia +591',
				'Pindorama +55',
				'Kanatã +1',
				'Chile +56',
				'Tetã China +86',
				'Kolómbia +57',
				'Yvykorea +82',
				'Costa Rícagui +506',
				'Ndinamayka +45',
				'Ekuator +593',
				'Pe Salvador +503',
				'Aravia Emiryvy Joaju +971',
				'España +34',
				'Estados Unídospe káda +1',
				'Filipinas +63',
				'Hyãsia +33',
				'Guatemala +502',
				'Honduras +504',
				'India +91',
				'Ilandia +353',
				'Israel +972',
				'Italia +39',
				'Hapõ +81',
				'Luxemburgo +352',
				'Méjiko +52',
				'Múnich +377',
				'Ojeproivírõ +505',
				'Nigériape +234',
				'Nueva Zelandaygua +64',
				'Holandaygua +31',
				'Panamáme oĩ +507',
				'Paraguái +595',
				'Perũ +51',
				'Poytuga +351',
				'Tavetã Joaju +44',
				'República Dominicanagua +1809',
				'Rrusia +7',
				'San Marino +378',
				'Suízape +41',
				'Ukyaña +380',
				'Uruguái +598',
				'Vaticano +39',
				'Venesuéla +58',
			],
			'ko': [
				'과테말라 +502',
				'나이지리아 +234',
				'네덜란드 +31',
				'뉴질랜드 +64',
				'니카라과 +505',
				'대한민국 +82',
				'덴마크 +45',
				'도미니카 공화국 +1809',
				'독일 +49',
				'러시아 +7',
				'룩셈부르크 +352',
				'멕시코 +52',
				'모나코 +377',
				'미국 +1',
				'바티칸 +39',
				'베네수엘라 +58',
				'벨기에 +32',
				'볼리비아 +591',
				'브라질 +55',
				'사우디 아라비아 +966',
				'산 마리노 +378',
				'스위스 +41',
				'스페인 +34',
				'아랍 에미리트 +971',
				'아르헨티나 +54',
				'아일랜드 +353',
				'앙골라 +244',
				'에콰도르 +593',
				'엘살바도르 +503',
				'영국 +44',
				'오스트레일리아 +61',
				'오스트리아 +43',
				'온두라스 +504',
				'우루과이 +598',
				'우크라이나 +380',
				'이스라엘 +972',
				'이탈리아 +39',
				'인도 +91',
				'일본 +81',
				'중국 +86',
				'칠레 +56',
				'캐나다 +1',
				'코스타리카 +506',
				'콜롬비아 +57',
				'파나마 +507',
				'파라과이 +595',
				'페루 +51',
				'포르투갈 +351',
				'프랑스 +33',
				'필리핀 +63',
			],
			'ru': [
				'Австралия +61',
				'Австрия +43',
				'Ангола +244',
				'Аргентина +54',
				'Бельгия +32',
				'Боливия +591',
				'Бразилия +55',
				'Ватикан +39',
				'Великобритания +44',
				'Венесуэла +58',
				'Гватемала +502',
				'Германия +49',
				'Гондурас +504',
				'Дания +45',
				'Доминиканская Республика +1809',
				'Израиль +972',
				'Индия +91',
				'Ирландия +353',
				'Испания +34',
				'Италия +39',
				'Канада +1',
				'Китай +86',
				'Колумбия +57',
				'Коста-Рика +506',
				'Люксембург +352',
				'Мексика +52',
				'Монако +377',
				'Нигерия +234',
				'Нидерланды +31',
				'Никарагуа +505',
				'Новая Зеландия +64',
				'Объединенные Арабские Эмираты +971',
				'Панама +507',
				'Парагвай +595',
				'Перу +51',
				'Португалия +351',
				'Россия +7',
				'Сальвадор +503',
				'Сан-Марино +378',
				'Саудовская Аравия +966',
				'США +1',
				'Украина +380',
				'Уругвай +598',
				'Филиппины +63',
				'Франция +33',
				'Чили +56',
				'Швейцария +41',
				'Эквадор +593',
				'Южная Корея +82',
				'Япония +81',
			],
			'yor': [
				'Amẹrika +1',
				'Angola +244',
				'Apapọ Arab Emirates +971',
				'Ará Argentina +54',
				'Australia +61',
				'Austria +43',
				'Bẹljiọmu +32',
				'Bolivia +591',
				'Chile +56',
				'Costa Rica +506',
				'Ecuador +593',
				'Egeskov +45',
				'El Salvador +503',
				'Faranse +33',
				'Fiorino +31',
				'Guatemala +502',
				'Guusu koria +82',
				'Honduras +504',
				'Ilu Bánándì +55',
				'Ilu Columbia +57',
				'Ilu Italia +39',
				'Ilu Pọtugali +351',
				'India +91',
				'Ireland +353',
				'Israeli +972',
				'Japan +81',
				'Jẹmánì +49',
				'Kanada +1',
				'Luxembourg +352',
				'Meksiko +52',
				'Monaco +377',
				'Nàìjíríà +234',
				'New Zealand +64',
				'Nicaragua +505',
				'Orilẹ-ede Dominican +1809',
				'Panama +507',
				'Paraguay +595',
				'Perú +51',
				'Philippines +63',
				'Russia +7',
				'Ṣaina +86',
				'San Marino +378',
				'Saudi Arabia +966',
				'Sibeeni +34',
				'Siwitsalandi +41',
				'United Kingdom +44',
				'Urugue +598',
				'Vatican +39',
				'Venezuela +58',
				'Yukirenia +380',
			],
			'he': [
				'אוסטריה +43',
				'אוסטרליה +61',
				'אוקראינה +380',
				'אורוגוואי +598',
				'איחוד האמירויות הערביות +971',
				'איטליה +39',
				'אירלנד +353',
				'אל סלבדור +503',
				'אנגולה +244',
				'אקוודור +593',
				'ארגנטינה +54',
				'ארצות הברית +1',
				'בוליביה +591',
				'בלגיה +32',
				'ברזיל +55',
				'בריטניה +44',
				'גואטמלה +502',
				'גרמניה +49',
				'דנמרק +45',
				'דרום קוריאה +82',
				'הודו +91',
				'הוותיקן +39',
				'הולנד +31',
				'הונדורס +504',
				'הפיליפינים +63',
				'הרפובליקה הדומיניקנית +1809',
				'ונצואלה +58',
				'יפן +81',
				'ישראל +972',
				'לוקסמבורג +352',
				'מונקו +377',
				'מקסיקו +52',
				'ניגריה +234',
				'ניו זילנד +64',
				'ניקרגואה +505',
				'סין +86',
				'סן מרינו +378',
				'סעודיה +966',
				'ספרד +34',
				'פורטוגל +351',
				'פנמה +507',
				'פרגוואי +595',
				'פרו +51',
				"צ'ילה +56",
				'צרפת +33',
				'קולומביה +57',
				'קוסטה ריקה +506',
				'קנדה +1',
				'רוסיה +7',
				'שוויץ +41',
			],
			'uk': [
				'Австралія +61',
				'Австрія +43',
				'Ангола +244',
				'Аргентина +54',
				'Бельгія +32',
				'Болівія +591',
				'Бразилія +55',
				'Ватикан +39',
				'Великобританія +44',
				'Венесуела +58',
				'Гватемала +502',
				'Гондурас +504',
				'Данія +45',
				'Домініканська Республіка +1809',
				'Еквадор +593',
				'Ізраїль +972',
				'Індія +91',
				'Ірландія +353',
				'Іспанія +34',
				'Італія +39',
				'Канада +1',
				'Китай +86',
				'Колумбія +57',
				'Коста-Ріка +506',
				'Люксембург +352',
				'Мексика +52',
				'Монако +377',
				'Нігерія +234',
				'Нідерланди +31',
				'Нікарагуа +505',
				'Німеччина +49',
				'Нова Зеландія +64',
				"Об'єднані Арабські Емірати +971",
				'Панама +507',
				'Парагвай +595',
				'Перу +51',
				'Південна Корея +82',
				'Португалія +351',
				'Росія +7',
				'Сальвадор +503',
				'Сан-Марино +378',
				'Саудівська Аравія +966',
				'США +1',
				'Україна +380',
				'Уругвай +598',
				'Філіппіни +63',
				'Франція +33',
				'Чилі +56',
				'Швейцарія +41',
				'Японія +81',
			],
			'la': [
				'Aequatoria +593',
				'Angola +244',
				'Arabia Saudita +966',
				'Argentina +54',
				'Australia +61',
				'Austria +43',
				'Belgium +32',
				'Bolivia +591',
				'Brasilia +55',
				'Britanniarum regnum +44',
				'Canada +1',
				'Chile +56',
				'Civitates Foederatae +1',
				'Colombia +57',
				'Costa Rica +506',
				'Dania +45',
				'Emiratus Arabici Coniuncti +971',
				'Gallia +33',
				'Germania +49',
				'Helvetia +41',
				'Hibernia +353',
				'Hispaniam +34',
				'Honduria +504',
				'Iaponia +81',
				'India +91',
				'Israel +972',
				'Italia +39',
				'Luxemburgum +352',
				'Mexico +52',
				'Monoecus +377',
				'Netherlands +31',
				'Nicaragua +505',
				'Nigeria +234',
				'Nova Zelandia +64',
				'Panama +507',
				'Paraquaria +595',
				'Peruvia +51',
				'Philippinae +63',
				'Portugal +351',
				'Res publica Coreana +82',
				'Res publica Dominiciana +1809',
				'Res publica Sancti Marini +378',
				'Russia +7',
				'Salvatoria +503',
				'Sinis +86',
				'Ucraina +380',
				'Uraquaria +598',
				'Vat +39',
				'Venetiola +58',
				'Vivamus +502',
			],
		}

		if cur_language in texto.keys():
			for dado in texto[cur_language]:
				temp = {
					'NomeOriginal': dado,
					'id': dado.replace(' ', '')
				}
				alerta.append(temp)
		else:
			for dado in texto['en']:
				temp = {
					'NomeOriginal': dado,
					'id': dado.replace(' ', '')
				}
				alerta.append(temp)

		# print(alerta)

		return HttpResponse(alerta)
