# """mysite URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/dev/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

# """

from django.urls import path
from django.conf.urls import include, re_path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # melhorar urls para padrão rest
    # path('itens', views.ItensView, name='Itens'),
    # path(
    #     'cadastro/parte',
    #     views.Contrato,
    #     name='Cadastro'
    # ),
    # path(
    #     'clausulas/cadastro',
    #     views.clausulasView.as_view(),
    #     name='teste_clausulas'
    # ),
    # path(
    #     'documento',
    #     views.contratoView.as_view(),
    #     name='teste_documento'
    # ),
    # path(
    #     'clausulas/visualizador',
    #     views.VisualizadordeClausulas,
    #     name='visualizadordeclausulas'
    # ),
    path(
        'accounts/',
        include('django.contrib.auth.urls'),
    ),
    path(
        'registration/',
        CadastroView.as_view(),
        name='registration'
    ),
        path(
        'LanguageCode/',
        LanguageCodeAPIView.as_view(),
        name='languagecode'
    ),
    path(
        'PalavraChave/',
        PalavraChaveAPIView.as_view(),
        name='palavrachave'
    ),
    path(
        'TipoBancoImagem/',
        TipoBancoImagemAPIView.as_view(),
        name='tipobancoimagem'
    ),
    path(
        'BancoImagem/',
        BancoImagemAPIView.as_view(),
        name='bancoimagem'
    ),
    path(
        'Continente/',
        ContinenteAPIView.as_view(),
        name='continente'
    ),
    path(
        'TipoHemisferio/',
        TipoHemisferioAPIView.as_view(),
        name='tipohemisferio'
    ),
    path(
        'AreaGeografica/',
        AreaGeograficaAPIView.as_view(),
        name='areageografica'
    ),
    path(
        'Pais/',
        PaisAPIView.as_view(),
        name='pais'
    ),
    path(
        'Regiao/',
        RegiaoAPIView.as_view(),
        name='regiao'
    ),
    path(
        'TipoOrgaoEmiss/',
        TipoOrgaoEmissAPIView.as_view(),
        name='tipoorgaoemiss'
    ),
    path(
        'Estado/',
        EstadoAPIView.as_view(),
        name='estado'
    ),
    path(
        'Cidade/',
        CidadeAPIView.as_view(),
        name='cidade'
    ),
    path(
        'TipoLogradouro/',
        TipoLogradouroAPIView.as_view(),
        name='tipologradouro'
    ),
    path(
        'CodigoEndPostal/',
        CodigoEndPostalAPIView.as_view(),
        name='codigoendpostal'
    ),
    path(
        'TipoComplemento/',
        TipoComplementoAPIView.as_view(),
        name='tipocomplemento'
    ),
    path(
        'TipoEndereco/',
        TipoEnderecoAPIView.as_view(),
        name='tipoendereco'
    ),
    path(
        'Endereco/',
        EnderecoAPIView.as_view(),
        name='endereco'
    ),
    path(
        'TipoContatoTecn/',
        TipoContatoTecnAPIView.as_view(),
        name='tipocontatotecn'
    ),
    path(
        'TipoContato/',
        TipoContatoAPIView.as_view(),
        name='tipocontato'
    ),
    path(
        'TipoOpTelefonia/',
        TipoOpTelefoniaAPIView.as_view(),
        name='tipooptelefonia'
    ),
    path(
        'Contato/',
        ContatoAPIView.as_view(),
        name='contato'
    ),
    path(
        'TipoPcDCateg/',
        TipoPcDCategAPIView.as_view(),
        name='tipopcdcateg'
    ),
    path(
        'TipoDiaSemana/',
        TipoDiaSemanaAPIView.as_view(),
        name='tipodiasemana'
    ),
    path(
        'TipoHorarioFuncionamento/',
        TipoHorarioFuncionamentoAPIView.as_view(),
        name='tipohorariofuncionamento'
    ),
    path(
        'HorarioFuncionamento/',
        HorarioFuncionamentoAPIView.as_view(),
        name='horariofuncionamento'
    ),
    path(
        'TipoUrl/',
        TipoUrlAPIView.as_view(),
        name='tipourl'
    ),
    path(
        'Url/',
        UrlAPIView.as_view(),
        name='url'
    ),
    path(
        'TipoPDV/',
        TipoPDVAPIView.as_view(),
        name='tipopdv'
    ),
    path(
        'PDV/',
        PDVAPIView.as_view(),
        name='pdv'
    ),
    path(
        'ItemTipoArea/',
        ItemTipoAreaAPIView.as_view(),
        name='itemtipoarea'
    ),
    path(
        'Microsite/',
        MicrositeAPIView.as_view(),
        name='microsite'
    ),
    path(
        'Unidade/',
        UnidadeAPIView.as_view(),
        name='unidade'
    ),
    path(
        'TipoPromocao/',
        TipoPromocaoAPIView.as_view(),
        name='tipopromocao'
    ),
    path(
        'TipoProgressao/',
        TipoProgressaoAPIView.as_view(),
        name='tipoprogressao'
    ),
    path(
        'TipoCargo/',
        TipoCargoAPIView.as_view(),
        name='tipocargo'
    ),
    path(
        'TipoDocumento/',
        TipoDocumentoAPIView.as_view(),
        name='tipodocumento'
    ),
    path(
        'TipoSetor/',
        TipoSetorAPIView.as_view(),
        name='tiposetor'
    ),
    path(
        'TipoFuncioTurno/',
        TipoFuncioTurnoAPIView.as_view(),
        name='tipofuncioturno'
    ),
    path(
        'TipoRelacao/',
        TipoRelacaoAPIView.as_view(),
        name='tiporelacao'
    ),
    path(
        'Cargo/',
        CargoAPIView.as_view(),
        name='cargo'
    ),
    path(
        'TipoCargoTrad/',
        TipoCargoTradAPIView.as_view(),
        name='tipocargotrad'
    ),
    path(
        'TipoCtrlQualidade/',
        TipoCtrlQualidadeAPIView.as_view(),
        name='tipoctrlqualidade'
    ),
    path(
        'TipoProficienciaLingua/',
        TipoProficienciaLinguaAPIView.as_view(),
        name='tipoproficiencialingua'
    ),
    path(
        'TipoMoeda/',
        TipoMoedaAPIView.as_view(),
        name='tipomoeda'
    ),
    path(
        'TipoVolumeAcumuladoVenda/',
        TipoVolumeAcumuladoVendaAPIView.as_view(),
        name='tipovolumeacumuladovenda'
    ),
    path(
        'TipoDomUmGdArCo/',
        TipoDomUmGdArCoAPIView.as_view(),
        name='tipodomumgdarco'
    ),
    path(
        'TipoDomUmSbArCo/',
        TipoDomUmSbArCoAPIView.as_view(),
        name='tipodomumsbarco'
    ),
    path(
        'TipoDominioUm/',
        TipoDominioUmAPIView.as_view(),
        name='tipodominioum'
    ),
    path(
        'TipoLinguaClasf/',
        TipoLinguaClasfAPIView.as_view(),
        name='tipolinguaclasf'
    ),
    path(
        'Lingua/',
        LinguaAPIView.as_view(),
        name='lingua'
    ),
    path(
        'TipoImposto/',
        TipoImpostoAPIView.as_view(),
        name='tipoimposto'
    ),
    path(
        'TipoNotaComunicacao/',
        TipoNotaComunicacaoAPIView.as_view(),
        name='tiponotacomunicacao'
    ),
    path(
        'TipoNotaQualidade/',
        TipoNotaQualidadeAPIView.as_view(),
        name='tiponotaqualidade'
    ),
    path(
        'TipoNotaGeral/',
        TipoNotaGeralAPIView.as_view(),
        name='tiponotageral'
    ),
    path(
        'CtrlQualidade/',
        CtrlQualidadeAPIView.as_view(),
        name='ctrlqualidade'
    ),
    path(
        'TipoMargemLucro/',
        TipoMargemLucroAPIView.as_view(),
        name='tipomargemlucro'
    ),
    path(
        'MargemLucro/',
        MargemLucroAPIView.as_view(),
        name='margemlucro'
    ),
    path(
        'Titulo/',
        TituloAPIView.as_view(),
        name='titulo'
    ),
    path(
        'SubTituloServico/',
        SubTituloServicoAPIView.as_view(),
        name='subtituloservico'
    ),
    path(
        'SubTipoDocumento/',
        SubTipoDocumentoAPIView.as_view(),
        name='subtipodocumento'
    ),
    path(
        'ItemCategoria/',
        ItemCategoriaAPIView.as_view(),
        name='itemcategoria'
    ),
    path(
        'TipoDomDoisSec/',
        TipoDomDoisSecAPIView.as_view(),
        name='tipodomdoissec'
    ),
    path(
        'TipoDomDoisDiv/',
        TipoDomDoisDivAPIView.as_view(),
        name='tipodomdoisdiv'
    ),
    path(
        'TipoDomDoisGrup/',
        TipoDomDoisGrupAPIView.as_view(),
        name='tipodomdoisgrup'
    ),
    path(
        'TipoDomDoisClas/',
        TipoDomDoisClasAPIView.as_view(),
        name='tipodomdoisclas'
    ),
    path(
        'TipoDominioDois/',
        TipoDominioDoisAPIView.as_view(),
        name='tipodominiodois'
    ),
    path(
        'Funcao/',
        FuncaoAPIView.as_view(),
        name='funcao'
    ),
    path(
        'TipoExtCategoria/',
        TipoExtCategoriaAPIView.as_view(),
        name='tipoextcategoria'
    ),
    path(
        'TipoExtensao/',
        TipoExtensaoAPIView.as_view(),
        name='tipoextensao'
    ),
    path(
        'CodigoValidacao/',
        CodigoValidacaoAPIView.as_view(),
        name='codigovalidacao'
    ),
    path(
        'Imposto/',
        ImpostoAPIView.as_view(),
        name='imposto'
    ),
    path(
        'PadraoDocumento/',
        PadraoDocumentoAPIView.as_view(),
        name='padraodocumento'
    ),
    path(
        'BancoArquivo/',
        BancoArquivoAPIView.as_view(),
        name='bancoarquivo'
    ),
    path(
        'Item/',
        ItemAPIView.as_view(),
        name='item'
    ),
    path(
        'CapacidadeDiaria/',
        CapacidadeDiariaAPIView.as_view(),
        name='capacidadediaria'
    ),
    path(
        'TipoMedidaServ/',
        TipoMedidaServAPIView.as_view(),
        name='tipomedidaserv'
    ),
    path(
        'TipoMedida/',
        TipoMedidaAPIView.as_view(),
        name='tipomedida'
    ),
    path(
        'TipoCompLingua/',
        TipoCompLinguaAPIView.as_view(),
        name='tipocomplingua'
    ),
    path(
        'TipoAnoInicioAtuacao/',
        TipoAnoInicioAtuacaoAPIView.as_view(),
        name='tipoanoinicioatuacao'
    ),
    path(
        'Valor/',
        ValorAPIView.as_view(),
        name='valor'
    ),
    path(
        'TipoFuncaoTrad/',
        TipoFuncaoTradAPIView.as_view(),
        name='tipofuncaotrad'
    ),
    path(
        'PosicaoClausulaDocumento/',
        PosicaoClausulaDocumentoAPIView.as_view(),
        name='posicaoclausuladocumento'
    ),
    path(
        'TipoClausula/',
        TipoClausulaAPIView.as_view(),
        name='tipoclausula'
    ),
    path(
        'Clausula/',
        ClausulaAPIView.as_view(),
        name='clausula'
    ),
    path(
        'TipoIdentificacao/',
        TipoIdentificacaoAPIView.as_view(),
        name='tipoidentificacao'
    ),
    path(
        'Identificacao/',
        IdentificacaoAPIView.as_view(),
        name='identificacao'
    ),
    path(
        'TipoSituacao/',
        TipoSituacaoAPIView.as_view(),
        name='tiposituacao'
    ),
    path(
        'TipoCargoProjeto/',
        TipoCargoProjetoAPIView.as_view(),
        name='tipocargoprojeto'
    ),
    path(
        'TipoVinculo/',
        TipoVinculoAPIView.as_view(),
        name='tipovinculo'
    ),
    path(
        'TipoCtrlPrazo/',
        TipoCtrlPrazoAPIView.as_view(),
        name='tipoctrlprazo'
    ),
    path(
        'CtrlPrazo/',
        CtrlPrazoAPIView.as_view(),
        name='ctrlprazo'
    ),
    path(
        'Projeto/',
        ProjetoAPIView.as_view(),
        name='projeto'
    ),
    path(
        'Outorga/',
        OutorgaAPIView.as_view(),
        name='outorga'
    ),
    path(
        'TipoEmail/',
        TipoEmailAPIView.as_view(),
        name='tipoemail'
    ),
    path(
        'Email/',
        EmailAPIView.as_view(),
        name='email'
    ),
    path(
        'TipoDataDiaCard/',
        TipoDataDiaCardAPIView.as_view(),
        name='tipodatadiacard'
    ),
    path(
        'TipoDataAnoCard/',
        TipoDataAnoCardAPIView.as_view(),
        name='tipodataanocard'
    ),
    path(
        'TipoRedeSocial/',
        TipoRedeSocialAPIView.as_view(),
        name='tiporedesocial'
    ),
    path(
        'RedeSocial/',
        RedeSocialAPIView.as_view(),
        name='redesocial'
    ),
    path(
        'TipoPronomeTratamento/',
        TipoPronomeTratamentoAPIView.as_view(),
        name='tipopronometratamento'
    ),
    path(
        'Referencia/',
        ReferenciaAPIView.as_view(),
        name='referencia'
    ),
    path(
        'TipoAreaGeoAtu/',
        TipoAreaGeoAtuAPIView.as_view(),
        name='tipoareageoatu'
    ),
    path(
        'User/',
        UserAPIView.as_view(),
        name='user'
    ),
    path(
        'TipoFiliacao/',
        TipoFiliacaoAPIView.as_view(),
        name='tipofiliacao'
    ),
    path(
        'OrdemPagamentoBrasil/',
        OrdemPagamentoBrasilAPIView.as_view(),
        name='ordempagamentobrasil'
    ),
    path(
        'QRCode/',
        QRCodeAPIView.as_view(),
        name='qrcode'
    ),
    path(
        'TipoMetodoPgto/',
        TipoMetodoPgtoAPIView.as_view(),
        name='tipometodopgto'
    ),
    path(
        'TipoBanco/',
        TipoBancoAPIView.as_view(),
        name='tipobanco'
    ),
    path(
        'TipoConta/',
        TipoContaAPIView.as_view(),
        name='tipoconta'
    ),
    path(
        'DadoBancario/',
        DadoBancarioAPIView.as_view(),
        name='dadobancario'
    ),
    path(
        'TipoFaturacao/',
        TipoFaturacaoAPIView.as_view(),
        name='tipofaturacao'
    ),
    path(
        'TipoCriptomoeda/',
        TipoCriptomoedaAPIView.as_view(),
        name='tipocriptomoeda'
    ),
    path(
        'Criptomoeda/',
        CriptomoedaAPIView.as_view(),
        name='criptomoeda'
    ),
    path(
        'TipoPrimeiroDiaSemana/',
        TipoPrimeiroDiaSemanaAPIView.as_view(),
        name='tipoprimeirodiasemana'
    ),
    path(
        'TipoDispHoraSemana/',
        TipoDispHoraSemanaAPIView.as_view(),
        name='tipodisphorasemana'
    ),
    path(
        'TipoFacilidade/',
        TipoFacilidadeAPIView.as_view(),
        name='tipofacilidade'
    ),
    path(
        'TipoSegmentoInteresse/',
        TipoSegmentoInteresseAPIView.as_view(),
        name='tiposegmentointeresse'
    ),
    path(
        'TipoDataMesCard/',
        TipoDataMesCardAPIView.as_view(),
        name='tipodatamescard'
    ),
    path(
        'TipoTurnoTrab/',
        TipoTurnoTrabAPIView.as_view(),
        name='tipoturnotrab'
    ),
    path(
        'DispTurnoPreferido/',
        DispTurnoPreferidoAPIView.as_view(),
        name='dispturnopreferido'
    ),
    path(
        'TipoAmenidade/',
        TipoAmenidadeAPIView.as_view(),
        name='tipoamenidade'
    ),
    path(
        'TipoPagamentoOnline/',
        TipoPagamentoOnlineAPIView.as_view(),
        name='tipopagamentoonline'
    ),
    path(
        'PagamentoOnline/',
        PagamentoOnlineAPIView.as_view(),
        name='pagamentoonline'
    ),
    path(
        'TipoMarcador/',
        TipoMarcadorAPIView.as_view(),
        name='tipomarcador'
    ),
    path(
        'DispDiaPreferido/',
        DispDiaPreferidoAPIView.as_view(),
        name='dispdiapreferido'
    ),
    path(
        'TipoPerfilConta/',
        TipoPerfilContaAPIView.as_view(),
        name='tipoperfilconta'
    ),
    path(
        'TipoEmpresa/',
        TipoEmpresaAPIView.as_view(),
        name='tipoempresa'
    ),
    path(
        'TipoBandeiraCartao/',
        TipoBandeiraCartaoAPIView.as_view(),
        name='tipobandeiracartao'
    ),
    path(
        'CartaoCredito/',
        CartaoCreditoAPIView.as_view(),
        name='cartaocredito'
    ),
    path(
        'PersonificacaoDominio/',
        PersonificacaoDominioAPIView.as_view(),
        name='personificacaodominio'
    ),
    path(
        'TipoSocio/',
        TipoSocioAPIView.as_view(),
        name='tiposocio'
    ),
    path(
        'QuadroSocio/',
        QuadroSocioAPIView.as_view(),
        name='quadrosocio'
    ),
    path(
        'TipoFerramentaIntegracao/',
        TipoFerramentaIntegracaoAPIView.as_view(),
        name='tipoferramentaintegracao'
    ),
    path(
        'Integracao/',
        IntegracaoAPIView.as_view(),
        name='integracao'
    ),
    path(
        'TransfSWIFT/',
        TransfSWIFTAPIView.as_view(),
        name='transfswift'
    ),
    path(
        'TransfItalia/',
        TransfItaliaAPIView.as_view(),
        name='transfitalia'
    ),
    path(
        'TransfUniaoEuropeia/',
        TransfUniaoEuropeiaAPIView.as_view(),
        name='transfuniaoeuropeia'
    ),
    path(
        'EsquemaCor/',
        EsquemaCorAPIView.as_view(),
        name='esquemacor'
    ),
    path(
        'SaldoMensagem/',
        SaldoMensagemAPIView.as_view(),
        name='saldomensagem'
    ),
    path(
        'RanqueamentoGeral/',
        RanqueamentoGeralAPIView.as_view(),
        name='ranqueamentogeral'
    ),
    path(
        'Notificacao/',
        NotificacaoAPIView.as_view(),
        name='notificacao'
    ),
    path(
        'Comissao/',
        ComissaoAPIView.as_view(),
        name='comissao'
    ),
    path(
        'TipoRegimTribut/',
        TipoRegimTributAPIView.as_view(),
        name='tiporegimtribut'
    ),
    path(
        'TipoEmpresaTamanho/',
        TipoEmpresaTamanhoAPIView.as_view(),
        name='tipoempresatamanho'
    ),
    path(
        'TipoContrib/',
        TipoContribAPIView.as_view(),
        name='tipocontrib'
    ),
    path(
        'Empresa/',
        EmpresaAPIView.as_view(),
        name='empresa'
    ),
    path(
        'SalaAula/',
        SalaAulaAPIView.as_view(),
        name='salaaula'
    ),
    path(
        'TipoNivelAluno/',
        TipoNivelAlunoAPIView.as_view(),
        name='tiponivelaluno'
    ),
    path(
        'Turma/',
        TurmaAPIView.as_view(),
        name='turma'
    ),
    path(
        'TipoExtDigEdit/',
        TipoExtDigEditAPIView.as_view(),
        name='tipoextdigedit'
    ),
    path(
        'TipoPeriferico/',
        TipoPerifericoAPIView.as_view(),
        name='tipoperiferico'
    ),
    path(
        'TipoSistemaOperacional/',
        TipoSistemaOperacionalAPIView.as_view(),
        name='tiposistemaoperacional'
    ),
    path(
        'TipoSoftwareTraducao/',
        TipoSoftwareTraducaoAPIView.as_view(),
        name='tiposoftwaretraducao'
    ),
    path(
        'TipoSoftwareLocaliz/',
        TipoSoftwareLocalizAPIView.as_view(),
        name='tiposoftwarelocaliz'
    ),
    path(
        'TipoSoftwareDTP/',
        TipoSoftwareDTPAPIView.as_view(),
        name='tiposoftwaredtp'
    ),
    path(
        'TipoSoftwarePacEsc/',
        TipoSoftwarePacEscAPIView.as_view(),
        name='tiposoftwarepacesc'
    ),
    path(
        'TipoSoftwareModTresD/',
        TipoSoftwareModTresDAPIView.as_view(),
        name='tiposoftwaremodtresd'
    ),
    path(
        'TipoSoftwareTransc/',
        TipoSoftwareTranscAPIView.as_view(),
        name='tiposoftwaretransc'
    ),
    path(
        'TipoSoftwareLeitor/',
        TipoSoftwareLeitorAPIView.as_view(),
        name='tiposoftwareleitor'
    ),
    path(
        'TipoEngineGame/',
        TipoEngineGameAPIView.as_view(),
        name='tipoenginegame'
    ),
    path(
        'ProtocoloAtendimento/',
        ProtocoloAtendimentoAPIView.as_view(),
        name='protocoloatendimento'
    ),
    path(
        'TipoHardwareComputador/',
        TipoHardwareComputadorAPIView.as_view(),
        name='tipohardwarecomputador'
    ),
    path(
        'TipoBancoDados/',
        TipoBancoDadosAPIView.as_view(),
        name='tipobancodados'
    ),
    path(
        'TipoExtDiagramacao/',
        TipoExtDiagramacaoAPIView.as_view(),
        name='tipoextdiagramacao'
    ),
    path(
        'TipoExtAudio/',
        TipoExtAudioAPIView.as_view(),
        name='tipoextaudio'
    ),
    path(
        'TipoExtLocalizacao/',
        TipoExtLocalizacaoAPIView.as_view(),
        name='tipoextlocalizacao'
    ),
    path(
        'TipoExtVideo/',
        TipoExtVideoAPIView.as_view(),
        name='tipoextvideo'
    ),
    path(
        'TipoIntervaloTempo/',
        TipoIntervaloTempoAPIView.as_view(),
        name='tipointervalotempo'
    ),
    path(
        'TipoParte/',
        TipoParteAPIView.as_view(),
        name='tipoparte'
    ),
    path(
        'TipoInstCertific/',
        TipoInstCertificAPIView.as_view(),
        name='tipoinstcertific'
    ),
    path(
        'ExameProficiencia/',
        ExameProficienciaAPIView.as_view(),
        name='exameproficiencia'
    ),
    path(
        'TipoExtDigNaoEdit/',
        TipoExtDigNaoEditAPIView.as_view(),
        name='tipoextdignaoedit'
    ),
    path(
        'TipoReligiao/',
        TipoReligiaoAPIView.as_view(),
        name='tiporeligiao'
    ),
    path(
        'TipoHobbie/',
        TipoHobbieAPIView.as_view(),
        name='tipohobbie'
    ),
    path(
        'TipoAcessoInternet/',
        TipoAcessoInternetAPIView.as_view(),
        name='tipoacessointernet'
    ),
    path(
        'TipoExpLocaliza/',
        TipoExpLocalizaAPIView.as_view(),
        name='tipoexplocaliza'
    ),
    path(
        'ParteTraducao/',
        ParteTraducaoAPIView.as_view(),
        name='partetraducao'
    ),
    path(
        'TipoFonte/',
        TipoFonteAPIView.as_view(),
        name='tipofonte'
    ),
    path(
        'AssinaturaDigital/',
        AssinaturaDigitalAPIView.as_view(),
        name='assinaturadigital'
    ),
    path(
        'DispHoraSemana/',
        DispHoraSemanaAPIView.as_view(),
        name='disphorasemana'
    ),
    path(
        'BancoCurriculo/',
        BancoCurriculoAPIView.as_view(),
        name='bancocurriculo'
    ),
    path(
        'TipoRelacionamento/',
        TipoRelacionamentoAPIView.as_view(),
        name='tiporelacionamento'
    ),
    path(
        'Relacionamento/',
        RelacionamentoAPIView.as_view(),
        name='relacionamento'
    ),
    path(
        'TipoUnidComprimento/',
        TipoUnidComprimentoAPIView.as_view(),
        name='tipounidcomprimento'
    ),
    path(
        'TipoUnidMassa/',
        TipoUnidMassaAPIView.as_view(),
        name='tipounidmassa'
    ),
    path(
        'Parte/',
        ParteAPIView.as_view(),
        name='parte'
    ),
    path(
        'Secao/',
        SecaoAPIView.as_view(),
        name='secao'
    ),
    path(
        'TipoDesconto/',
        TipoDescontoAPIView.as_view(),
        name='tipodesconto'
    ),
    path(
        'Desconto/',
        DescontoAPIView.as_view(),
        name='desconto'
    ),
    path(
        'TipoComoConheceu/',
        TipoComoConheceuAPIView.as_view(),
        name='tipocomoconheceu'
    ),
    path(
        'OrdemExeServico/',
        OrdemExeServicoAPIView.as_view(),
        name='ordemexeservico'
    ),
    path(
        'Convenio/',
        ConvenioAPIView.as_view(),
        name='convenio'
    ),
    path(
        'TipoRelDiag/',
        TipoRelDiagAPIView.as_view(),
        name='tiporeldiag'
    ),
    path(
        'TipoModoEntrega/',
        TipoModoEntregaAPIView.as_view(),
        name='tipomodoentrega'
    ),
    path(
        'RelDiag/',
        RelDiagAPIView.as_view(),
        name='reldiag'
    ),
    path(
        'ItemModelo/',
        ItemModeloAPIView.as_view(),
        name='itemmodelo'
    ),
    path(
        'ItemModeloTraducao/',
        ItemModeloTraducaoAPIView.as_view(),
        name='itemmodelotraducao'
    ),
    path(
        'ItemTraducao/',
        ItemTraducaoAPIView.as_view(),
        name='itemtraducao'
    ),
    path(
        'TipoSuporteCont/',
        TipoSuporteContAPIView.as_view(),
        name='tiposuportecont'
    ),
    path(
        'TipoConteudoCategoria/',
        TipoConteudoCategoriaAPIView.as_view(),
        name='tipoconteudocategoria'
    ),
    path(
        'TipoConteudo/',
        TipoConteudoAPIView.as_view(),
        name='tipoconteudo'
    ),
    path(
        'TipoSuporteContIO/',
        TipoSuporteContIOAPIView.as_view(),
        name='tiposuportecontio'
    ),
    path(
        'TipoExtDigEdtIO/',
        TipoExtDigEdtIOAPIView.as_view(),
        name='tipoextdigedtio'
    ),
    path(
        'RelDiagServAd/',
        RelDiagServAdAPIView.as_view(),
        name='reldiagservad'
    ),
    path(
        'TipoFusoHorario/',
        TipoFusoHorarioAPIView.as_view(),
        name='tipofusohorario'
    ),
    path(
        'TipoAgenda/',
        TipoAgendaAPIView.as_view(),
        name='tipoagenda'
    ),
    path(
        'Agenda/',
        AgendaAPIView.as_view(),
        name='agenda'
    ),
    path(
        'AgendaDisponivel/',
        AgendaDisponivelAPIView.as_view(),
        name='agendadisponivel'
    ),
    path(
        'TipoStatusMensagem/',
        TipoStatusMensagemAPIView.as_view(),
        name='tipostatusmensagem'
    ),
    path(
        'TipoMensagem/',
        TipoMensagemAPIView.as_view(),
        name='tipomensagem'
    ),
    path(
        'Mensagem/',
        MensagemAPIView.as_view(),
        name='mensagem'
    ),
    path(
        'TipoFormCompl/',
        TipoFormComplAPIView.as_view(),
        name='tipoformcompl'
    ),
    path(
        'TipoCertificacao/',
        TipoCertificacaoAPIView.as_view(),
        name='tipocertificacao'
    ),
    path(
        'TipoDataMesOrdn/',
        TipoDataMesOrdnAPIView.as_view(),
        name='tipodatamesordn'
    ),
    path(
        'TipoPeriodoAnoAtual/',
        TipoPeriodoAnoAtualAPIView.as_view(),
        name='tipoperiodoanoatual'
    ),
    path(
        'TipoStatusForm/',
        TipoStatusFormAPIView.as_view(),
        name='tipostatusform'
    ),
    path(
        'TipoDuracaoCurso/',
        TipoDuracaoCursoAPIView.as_view(),
        name='tipoduracaocurso'
    ),
    path(
        'TipoUnidTempo/',
        TipoUnidTempoAPIView.as_view(),
        name='tipounidtempo'
    ),
    path(
        'FormCompl/',
        FormComplAPIView.as_view(),
        name='formcompl'
    ),
    path(
        'TipoFormAcadem/',
        TipoFormAcademAPIView.as_view(),
        name='tipoformacadem'
    ),
    path(
        'FormAcadem/',
        FormAcademAPIView.as_view(),
        name='formacadem'
    ),
    path(
        'TipoDiaSemTrad/',
        TipoDiaSemTradAPIView.as_view(),
        name='tipodiasemtrad'
    ),
    path(
        'TipoDataDiaOrdn/',
        TipoDataDiaOrdnAPIView.as_view(),
        name='tipodatadiaordn'
    ),
    path(
        'TipoDataComDetl/',
        TipoDataComDetlAPIView.as_view(),
        name='tipodatacomdetl'
    ),
    path(
        'TipoDataComAssu/',
        TipoDataComAssuAPIView.as_view(),
        name='tipodatacomassu'
    ),
    path(
        'TipoDataCom/',
        TipoDataComAPIView.as_view(),
        name='tipodatacom'
    ),
    path(
        'TipoEstagioProposta/',
        TipoEstagioPropostaAPIView.as_view(),
        name='tipoestagioproposta'
    ),
    path(
        'PropTecComercial/',
        PropTecComercialAPIView.as_view(),
        name='propteccomercial'
    ),
    path(
        'TipoPeriodicidade/',
        TipoPeriodicidadeAPIView.as_view(),
        name='tipoperiodicidade'
    ),
    path(
        'Lembrete/',
        LembreteAPIView.as_view(),
        name='lembrete'
    ),
    path(
        'AgendaAtividade/',
        AgendaAtividadeAPIView.as_view(),
        name='agendaatividade'
    ),
    path(
        'Combo/',
        ComboAPIView.as_view(),
        name='combo'
    ),
    path(
        'ItemUnidade/',
        ItemUnidadeAPIView.as_view(),
        name='itemunidade'
    ),
    path(
        'Produto/',
        ProdutoAPIView.as_view(),
        name='produto'
    ),
    path(
        'TipoLingua/',
        TipoLinguaAPIView.as_view(),
        name='tipolingua'
    ),
    path(
        'RelDiagLinguaPais/',
        RelDiagLinguaPaisAPIView.as_view(),
        name='reldiaglinguapais'
    ),
    path(
        'TipoDispAmbient/',
        TipoDispAmbientAPIView.as_view(),
        name='tipodispambient'
    ),
    path(
        'TipoAutodeclaracao/',
        TipoAutodeclaracaoAPIView.as_view(),
        name='tipoautodeclaracao'
    ),
    path(
        'EventoInterpCargo/',
        EventoInterpCargoAPIView.as_view(),
        name='eventointerpcargo'
    ),
    path(
        'RepeticaoInterpretacao/',
        RepeticaoInterpretacaoAPIView.as_view(),
        name='repeticaointerpretacao'
    ),
    path(
        'RepeticaoEvento/',
        RepeticaoEventoAPIView.as_view(),
        name='repeticaoevento'
    ),
    path(
        'NumeroRecepAuriculares/',
        NumeroRecepAuricularesAPIView.as_view(),
        name='numerorecepauriculares'
    ),
    path(
        'EventoDetalhe/',
        EventoDetalheAPIView.as_view(),
        name='eventodetalhe'
    ),
    path(
        'Responsavel/',
        ResponsavelAPIView.as_view(),
        name='responsavel'
    ),
    path(
        'TipoLocalPresencial/',
        TipoLocalPresencialAPIView.as_view(),
        name='tipolocalpresencial'
    ),
    path(
        'TipoPreferenciaAula/',
        TipoPreferenciaAulaAPIView.as_view(),
        name='tipopreferenciaaula'
    ),
    path(
        'TipoFaixaEtaria/',
        TipoFaixaEtariaAPIView.as_view(),
        name='tipofaixaetaria'
    ),
    path(
        'TipoRegimeEnsino/',
        TipoRegimeEnsinoAPIView.as_view(),
        name='tiporegimeensino'
    ),
    path(
        'TipoModalidade/',
        TipoModalidadeAPIView.as_view(),
        name='tipomodalidade'
    ),
    path(
        'TipoRepeticaoCurso/',
        TipoRepeticaoCursoAPIView.as_view(),
        name='tiporepeticaocurso'
    ),
    path(
        'RelDiagCurso/',
        RelDiagCursoAPIView.as_view(),
        name='reldiagcurso'
    ),
    path(
        'TipoResidenciaContrato/',
        TipoResidenciaContratoAPIView.as_view(),
        name='tiporesidenciacontrato'
    ),
    path(
        'TipoHabilitacao/',
        TipoHabilitacaoAPIView.as_view(),
        name='tipohabilitacao'
    ),
    path(
        'TipoPcDAparelho/',
        TipoPcDAparelhoAPIView.as_view(),
        name='tipopcdaparelho'
    ),
    path(
        'TipoEstadoCivil/',
        TipoEstadoCivilAPIView.as_view(),
        name='tipoestadocivil'
    ),
    path(
        'TipoResidencia/',
        TipoResidenciaAPIView.as_view(),
        name='tiporesidencia'
    ),
    path(
        'TipoTrabalhoVoluntario/',
        TipoTrabalhoVoluntarioAPIView.as_view(),
        name='tipotrabalhovoluntario'
    ),
    path(
        'TipoMorador/',
        TipoMoradorAPIView.as_view(),
        name='tipomorador'
    ),
    path(
        'TipoRendaFamiliar/',
        TipoRendaFamiliarAPIView.as_view(),
        name='tiporendafamiliar'
    ),
    path(
        'TipoFilhoQuant/',
        TipoFilhoQuantAPIView.as_view(),
        name='tipofilhoquant'
    ),
    path(
        'DadosPessoais/',
        DadosPessoaisAPIView.as_view(),
        name='dadospessoais'
    ),
    path(
        'TipoImovel/',
        TipoImovelAPIView.as_view(),
        name='tipoimovel'
    ),
    path(
        'TipoFuncionarioQuant/',
        TipoFuncionarioQuantAPIView.as_view(),
        name='tipofuncionarioquant'
    ),
    path(
        'TipoLicFranquia/',
        TipoLicFranquiaAPIView.as_view(),
        name='tipolicfranquia'
    ),
    path(
        'TipoInvestimentoInicial/',
        TipoInvestimentoInicialAPIView.as_view(),
        name='tipoinvestimentoinicial'
    ),
    path(
        'TipoCapitalGiro/',
        TipoCapitalGiroAPIView.as_view(),
        name='tipocapitalgiro'
    ),
    path(
        'TipoAreaMinima/',
        TipoAreaMinimaAPIView.as_view(),
        name='tipoareaminima'
    ),
    path(
        'TipoCompartGeo/',
        TipoCompartGeoAPIView.as_view(),
        name='tipocompartgeo'
    ),
    path(
        'RelDiagLicFranquia/',
        RelDiagLicFranquiaAPIView.as_view(),
        name='reldiaglicfranquia'
    ),
    path(
        'RelDiagTrad/',
        RelDiagTradAPIView.as_view(),
        name='reldiagtrad'
    ),
    path(
        'EventoEndereco/',
        EventoEnderecoAPIView.as_view(),
        name='eventoendereco'
    ),
    path(
        'TipoEvento/',
        TipoEventoAPIView.as_view(),
        name='tipoevento'
    ),
    path(
        'Evento/',
        EventoAPIView.as_view(),
        name='evento'
    ),
    path(
        'TipoPretensaoBolsaEstagio/',
        TipoPretensaoBolsaEstagioAPIView.as_view(),
        name='tipopretensaobolsaestagio'
    ),
    path(
        'TipoProgrIcentEducacao/',
        TipoProgrIcentEducacaoAPIView.as_view(),
        name='tipoprogricenteducacao'
    ),
    path(
        'TipoDisponibilEstagiar/',
        TipoDisponibilEstagiarAPIView.as_view(),
        name='tipodisponibilestagiar'
    ),
    path(
        'TipoTurnoEdu/',
        TipoTurnoEduAPIView.as_view(),
        name='tipoturnoedu'
    ),
    path(
        'ItemBolsaEstagio/',
        ItemBolsaEstagioAPIView.as_view(),
        name='itembolsaestagio'
    ),
    path(
        'Livro/',
        LivroAPIView.as_view(),
        name='livro'
    ),
    path(
        'RelDiagLivraria/',
        RelDiagLivrariaAPIView.as_view(),
        name='reldiaglivraria'
    ),
    path(
        'CabecalhoTopo/',
        CabecalhoTopoAPIView.as_view(),
        name='cabecalhotopo'
    ),
    path(
        'Rodape/',
        RodapeAPIView.as_view(),
        name='rodape'
    ),
    path(
        'RodapeMenu/',
        RodapeMenuAPIView.as_view(),
        name='rodapemenu'
    ),
    path(
        'RodapeBase/',
        RodapeBaseAPIView.as_view(),
        name='rodapebase'
    ),
    path(
        'Cabecalho/',
        CabecalhoAPIView.as_view(),
        name='cabecalho'
    ),
    path(
        'CabecalhoMenu/',
        CabecalhoMenuAPIView.as_view(),
        name='cabecalhomenu'
    ),
    path(
        'Principal/',
        PrincipalAPIView.as_view(),
        name='principal'
    ),
    path(
        'Site/',
        SiteAPIView.as_view(),
        name='site'
    ),
    path(
        'TipoPainelAtendimento/',
        TipoPainelAtendimentoAPIView.as_view(),
        name='tipopainelatendimento'
    ),
    path(
        'TipoPosicaoAtendimento/',
        TipoPosicaoAtendimentoAPIView.as_view(),
        name='tipoposicaoatendimento'
    ),
    path(
        'TipoOrientacao/',
        TipoOrientacaoAPIView.as_view(),
        name='tipoorientacao'
    ),
    path(
        'PainelAtendimento/',
        PainelAtendimentoAPIView.as_view(),
        name='painelatendimento'
    ),
    path(
        'TipoClienteAtende/',
        TipoClienteAtendeAPIView.as_view(),
        name='tipoclienteatende'
    ),
    path(
        'FormatoHora/',
        FormatoHoraAPIView.as_view(),
        name='formatohora'
    ),
    path(
        'TipoSituacOcup/',
        TipoSituacOcupAPIView.as_view(),
        name='tiposituacocup'
    ),
    path(
        'TipoFormatoData/',
        TipoFormatoDataAPIView.as_view(),
        name='tipoformatodata'
    ),
    path(
        'PreferenciaAdicional/',
        PreferenciaAdicionalAPIView.as_view(),
        name='preferenciaadicional'
    ),
    path(
        'Software/',
        SoftwareAPIView.as_view(),
        name='software'
    ),
    path(
        'InstituicaoEnsino/',
        InstituicaoEnsinoAPIView.as_view(),
        name='instituicaoensino'
    ),
    path(
        'TipoServTerceiro/',
        TipoServTerceiroAPIView.as_view(),
        name='tiposervterceiro'
    ),
    path(
        'RelDiagServTerceiro/',
        RelDiagServTerceiroAPIView.as_view(),
        name='reldiagservterceiro'
    ),
    path(
        'ParteLinguaPais/',
        ParteLinguaPaisAPIView.as_view(),
        name='partelinguapais'
    ),
    path(
        'TipoNota/',
        TipoNotaAPIView.as_view(),
        name='tiponota'
    ),
    path(
        'Nota/',
        NotaAPIView.as_view(),
        name='nota'
    ),
    path(
        'ListaCampanha/',
        ListaCampanhaAPIView.as_view(),
        name='listacampanha'
    ),
    path(
        'EmpresaLinguaPais/',
        EmpresaLinguaPaisAPIView.as_view(),
        name='empresalinguapais'
    ),
    path(
        'TipoAcao/',
        TipoAcaoAPIView.as_view(),
        name='tipoacao'
    ),
    path(
        'AgendaPermissao/',
        AgendaPermissaoAPIView.as_view(),
        name='agendapermissao'
    ),
    path(
        'TipoClassLista/',
        TipoClassListaAPIView.as_view(),
        name='tipoclasslista'
    ),
    path(
        'TipoStatusLista/',
        TipoStatusListaAPIView.as_view(),
        name='tipostatuslista'
    ),
    path(
        'ListaContato/',
        ListaContatoAPIView.as_view(),
        name='listacontato'
    ),
    path(
        'ListaEmail/',
        ListaEmailAPIView.as_view(),
        name='listaemail'
    ),
    path(
        'Filme/',
        FilmeAPIView.as_view(),
        name='filme'
    ),
    path(
        'RelDiagLicPlano/',
        RelDiagLicPlanoAPIView.as_view(),
        name='reldiaglicplano'
    ),
    path(
        'ItemLocacaoBalcao/',
        ItemLocacaoBalcaoAPIView.as_view(),
        name='itemlocacaobalcao'
    ),
    path(
        'TipoAcaoCampanha/',
        TipoAcaoCampanhaAPIView.as_view(),
        name='tipoacaocampanha'
    ),
    path(
        'TipoStatusCampanha/',
        TipoStatusCampanhaAPIView.as_view(),
        name='tipostatuscampanha'
    ),
    path(
        'TipoCategoriaModeloCampanha/',
        TipoCategoriaModeloCampanhaAPIView.as_view(),
        name='tipocategoriamodelocampanha'
    ),
    path(
        'TipoModeloCampanha/',
        TipoModeloCampanhaAPIView.as_view(),
        name='tipomodelocampanha'
    ),
    path(
        'ModeloCampanha/',
        ModeloCampanhaAPIView.as_view(),
        name='modelocampanha'
    ),
    path(
        'Campanha/',
        CampanhaAPIView.as_view(),
        name='campanha'
    ),
    path(
        'TipoPerfilLocutor/',
        TipoPerfilLocutorAPIView.as_view(),
        name='tipoperfillocutor'
    ),
    path(
        'ItemTipoPerfilLocutor/',
        ItemTipoPerfilLocutorAPIView.as_view(),
        name='itemtipoperfillocutor'
    ),
    path(
        'TipoCategoriaServico/',
        TipoCategoriaServicoAPIView.as_view(),
        name='tipocategoriaservico'
    ),
    path(
        'ItemCategoriaServico/',
        ItemCategoriaServicoAPIView.as_view(),
        name='itemcategoriaservico'
    ),
    path(
        'TipoTamanho/',
        TipoTamanhoAPIView.as_view(),
        name='tipotamanho'
    ),
    path(
        'ModeloDocumento/',
        ModeloDocumentoAPIView.as_view(),
        name='modelodocumento'
    ),
    path(
        'TipoLicConvenio/',
        TipoLicConvenioAPIView.as_view(),
        name='tipolicconvenio'
    ),
    path(
        'RelDiagLicConvenio/',
        RelDiagLicConvenioAPIView.as_view(),
        name='reldiaglicconvenio'
    ),
    path(
        'MedidaNotaItem/',
        MedidaNotaItemAPIView.as_view(),
        name='medidanotaitem'
    ),
    path(
        'NotaItem/',
        NotaItemAPIView.as_view(),
        name='notaitem'
    ),
    path(
        'PrestadorPreferencial/',
        PrestadorPreferencialAPIView.as_view(),
        name='prestadorpreferencial'
    ),
    path(
        'Comercial/',
        ComercialAPIView.as_view(),
        name='comercial'
    ),
    path(
        'OpcaoMenu/',
        OpcaoMenuAPIView.as_view(),
        name='opcaomenu'
    ),
    path(
        'TipoPercPgto/',
        TipoPercPgtoAPIView.as_view(),
        name='tipopercpgto'
    ),
    path(
        'PgtoSinalCliente/',
        PgtoSinalClienteAPIView.as_view(),
        name='pgtosinalcliente'
    ),
    path(
        'TipoPercntDesmb/',
        TipoPercntDesmbAPIView.as_view(),
        name='tipopercntdesmb'
    ),
    path(
        'PgtoColab/',
        PgtoColabAPIView.as_view(),
        name='pgtocolab'
    ),
    path(
        'TipoEnderecamento/',
        TipoEnderecamentoAPIView.as_view(),
        name='tipoenderecamento'
    ),
    path(
        'Enderecamento/',
        EnderecamentoAPIView.as_view(),
        name='enderecamento'
    ),
    path(
        'TipoObraLiteraria/',
        TipoObraLiterariaAPIView.as_view(),
        name='tipoobraliteraria'
    ),
    path(
        'ItemObraLiteraria/',
        ItemObraLiterariaAPIView.as_view(),
        name='itemobraliteraria'
    ),
    path(
        'TipoObraCientifica/',
        TipoObraCientificaAPIView.as_view(),
        name='tipoobracientifica'
    ),
    path(
        'ItemObraCientifica/',
        ItemObraCientificaAPIView.as_view(),
        name='itemobracientifica'
    ),
    path(
        'TipoPcD/',
        TipoPcDAPIView.as_view(),
        name='tipopcd'
    ),
    path(
        'TipoItemCompEqpTempo/',
        TipoItemCompEqpTempoAPIView.as_view(),
        name='tipoitemcompeqptempo'
    ),
    path(
        'ItemCompEqp/',
        ItemCompEqpAPIView.as_view(),
        name='itemcompeqp'
    ),
    path(
        'TipoAssociacao/',
        TipoAssociacaoAPIView.as_view(),
        name='tipoassociacao'
    ),
    path(
        'AssociadoParte/',
        AssociadoParteAPIView.as_view(),
        name='associadoparte'
    ),
    path(
        'AssociadoEmpresa/',
        AssociadoEmpresaAPIView.as_view(),
        name='associadoempresa'
    ),
    path(
        'Associacao/',
        AssociacaoAPIView.as_view(),
        name='associacao'
    ),
    path(
        'TipoFluenciaVerb/',
        TipoFluenciaVerbAPIView.as_view(),
        name='tipofluenciaverb'
    ),
    path(
        'TipoPerfilGerentProjeto/',
        TipoPerfilGerentProjetoAPIView.as_view(),
        name='tipoperfilgerentprojeto'
    ),
    path(
        'ItemTipoPerfilGerProjeto/',
        ItemTipoPerfilGerProjetoAPIView.as_view(),
        name='itemtipoperfilgerprojeto'
    ),
    path(
        'ItemTipoEvento/',
        ItemTipoEventoAPIView.as_view(),
        name='itemtipoevento'
    ),
    path(
        'TipoSistemasInformacao/',
        TipoSistemasInformacaoAPIView.as_view(),
        name='tiposistemasinformacao'
    ),
    path(
        'ItemSistemasInformacao/',
        ItemSistemasInformacaoAPIView.as_view(),
        name='itemsistemasinformacao'
    ),
    path(
        'ItemTipoPcD/',
        ItemTipoPcDAPIView.as_view(),
        name='itemtipopcd'
    ),
    path(
        'TipoObraArtistica/',
        TipoObraArtisticaAPIView.as_view(),
        name='tipoobraartistica'
    ),
    path(
        'ItemObraArtistica/',
        ItemObraArtisticaAPIView.as_view(),
        name='itemobraartistica'
    ),
    path(
        'TipoVolumeMedioVendaSemanal/',
        TipoVolumeMedioVendaSemanalAPIView.as_view(),
        name='tipovolumemediovendasemanal'
    ),
    path(
        'TipoModulo/',
        TipoModuloAPIView.as_view(),
        name='tipomodulo'
    ),
    path(
        'Permissao/',
        PermissaoAPIView.as_view(),
        name='permissao'
    ),
    path(
        'TipoEstiloLocucao/',
        TipoEstiloLocucaoAPIView.as_view(),
        name='tipoestilolocucao'
    ),
    path(
        'ItemTipoEstiloLocucao/',
        ItemTipoEstiloLocucaoAPIView.as_view(),
        name='itemtipoestilolocucao'
    ),
    path(
        'TipoVozGenero/',
        TipoVozGeneroAPIView.as_view(),
        name='tipovozgenero'
    ),
    path(
        'ItemTipoVozGenero/',
        ItemTipoVozGeneroAPIView.as_view(),
        name='itemtipovozgenero'
    ),
    path(
        'TipoFocoLocucao/',
        TipoFocoLocucaoAPIView.as_view(),
        name='tipofocolocucao'
    ),
    path(
        'ItemTipoFocoLocucao/',
        ItemTipoFocoLocucaoAPIView.as_view(),
        name='itemtipofocolocucao'
    ),
    path(
        'TipoVozIdade/',
        TipoVozIdadeAPIView.as_view(),
        name='tipovozidade'
    ),
    path(
        'ItemTipoVozIdade/',
        ItemTipoVozIdadeAPIView.as_view(),
        name='itemtipovozidade'
    ),
    path(
        'TipoVozAmostra/',
        TipoVozAmostraAPIView.as_view(),
        name='tipovozamostra'
    ),
    path(
        'ItemTipoVozAmostra/',
        ItemTipoVozAmostraAPIView.as_view(),
        name='itemtipovozamostra'
    ),
    path(
        'AgendaAtividadeHistorico/',
        AgendaAtividadeHistoricoAPIView.as_view(),
        name='agendaatividadehistorico'
    ),
    path(
        'Hardware/',
        HardwareAPIView.as_view(),
        name='hardware'
    ),
    path(
        'TipoProficCateg/',
        TipoProficCategAPIView.as_view(),
        name='tipoproficcateg'
    ),
    path(
        'ParteLinguaPaisTipoProficCateg/',
        ParteLinguaPaisTipoProficCategAPIView.as_view(),
        name='partelinguapaistipoproficcateg'
    ),
    path(
        'ParEmpresaLinguaPais/',
        ParEmpresaLinguaPaisAPIView.as_view(),
        name='parempresalinguapais'
    ),
    path(
        'TipoFaseLua/',
        TipoFaseLuaAPIView.as_view(),
        name='tipofaselua'
    ),
    path(
        'TipoLingProg/',
        TipoLingProgAPIView.as_view(),
        name='tipolingprog'
    ),
    path(
        'ParteTipoLingProg/',
        ParteTipoLingProgAPIView.as_view(),
        name='partetipolingprog'
    ),
    path(
        'TipoLocacao/',
        TipoLocacaoAPIView.as_view(),
        name='tipolocacao'
    ),
    path(
        'RelDiagLocEquipamento/',
        RelDiagLocEquipamentoAPIView.as_view(),
        name='reldiaglocequipamento'
    ),
    path(
        'RelDiagInterpretacao/',
        RelDiagInterpretacaoAPIView.as_view(),
        name='reldiaginterpretacao'
    ),
    path(
        'Certificacao/',
        CertificacaoAPIView.as_view(),
        name='certificacao'
    ),
    path(
        'TipoRestricao/',
        TipoRestricaoAPIView.as_view(),
        name='tiporestricao'
    ),
    path(
        'TipoBiometria/',
        TipoBiometriaAPIView.as_view(),
        name='tipobiometria'
    ),
    path(
        'ListaRestricao/',
        ListaRestricaoAPIView.as_view(),
        name='listarestricao'
    ),
    path(
        'Biometria/',
        BiometriaAPIView.as_view(),
        name='biometria'
    ),
    path(
        'LinguaPais/',
        LinguaPaisAPIView.as_view(),
        name='linguapais'
    ),
    path(
        'TipoLicOportunidade/',
        TipoLicOportunidadeAPIView.as_view(),
        name='tipolicoportunidade'
    ),
    path(
        'RelDiagLicOportunidade/',
        RelDiagLicOportunidadeAPIView.as_view(),
        name='reldiaglicoportunidade'
    ),
    path(
        'Inventario/',
        InventarioAPIView.as_view(),
        name='inventario'
    ),
    path(
        'ConvenioParteEmpresa/',
        ConvenioParteEmpresaAPIView.as_view(),
        name='convenioparteempresa'
    ),
    path(
        'ConvenioItem/',
        ConvenioItemAPIView.as_view(),
        name='convenioitem'
    ),
    path(
        'LinguaPaisEmpresa/',
        LinguaPaisEmpresaAPIView.as_view(),
        name='linguapaisempresa'
    ),
    path(
        'EmpresaLinguaPaisTipoProficCateg/',
        EmpresaLinguaPaisTipoProficCategAPIView.as_view(),
        name='empresalinguapaistipoproficcateg'
    ),
    path(
        'ParEmpresaLinguaInstCertific/',
        ParEmpresaLinguaInstCertificAPIView.as_view(),
        name='parempresalinguainstcertific'
    ),
    path(
        'TipoEstacAno/',
        TipoEstacAnoAPIView.as_view(),
        name='tipoestacano'
    ),
    path(
        'TipoEstacAnoIni/',
        TipoEstacAnoIniAPIView.as_view(),
        name='tipoestacanoini'
    ),
    path(
        'TipoDataComDA/',
        TipoDataComDAAPIView.as_view(),
        name='tipodatacomda'
    ),
    path(
        'ParteTipoSuporteCont/',
        ParteTipoSuporteContAPIView.as_view(),
        name='partetiposuportecont'
    ),
    path(
        'RelDiagServAdClosedCaption/',
        RelDiagServAdClosedCaptionAPIView.as_view(),
        name='reldiagservadclosedcaption'
    ),
    path(
        'RelDiagServAdDigitacao/',
        RelDiagServAdDigitacaoAPIView.as_view(),
        name='reldiagservaddigitacao'
    ),
    path(
        'Consignado/',
        ConsignadoAPIView.as_view(),
        name='consignado'
    ),
    path(
        'ItemCompEqpCargo/',
        ItemCompEqpCargoAPIView.as_view(),
        name='itemcompeqpcargo'
    ),
    path(
        'BancoImagemTraducao/',
        BancoImagemTraducaoAPIView.as_view(),
        name='bancoimagemtraducao'
    ),
    path(
        'Auditoria/',
        AuditoriaAPIView.as_view(),
        name='auditoria'
    ),
    path(
        'LivroTraducao/',
        LivroTraducaoAPIView.as_view(),
        name='livrotraducao'
    ),
    path(
        'ItemLinguaPais/',
        ItemLinguaPaisAPIView.as_view(),
        name='itemlinguapais'
    ),
    path(
        'ExperienciaAdminTraducao/',
        ExperienciaAdminTraducaoAPIView.as_view(),
        name='experienciaadmintraducao'
    ),
    path(
        'ExperienciaComercialDescritiva/',
        ExperienciaComercialDescritivaAPIView.as_view(),
        name='experienciacomercialdescritiva'
    ),
    path(
        'Venda/',
        VendaAPIView.as_view(),
        name='venda'
    ),
    path(
        'TipoDataAnoOrdn/',
        TipoDataAnoOrdnAPIView.as_view(),
        name='tipodataanoordn'
    ),
    path(
        'EventoDetalheDominioUm/',
        EventoDetalheDominioUmAPIView.as_view(),
        name='eventodetalhedominioum'
    ),
    path(
        'RanqueamentoCargo/',
        RanqueamentoCargoAPIView.as_view(),
        name='ranqueamentocargo'
    ),
    path(
        'FilmeTraducao/',
        FilmeTraducaoAPIView.as_view(),
        name='filmetraducao'
    ),
    path(
        'AssinaturaBancoArquivo/',
        AssinaturaBancoArquivoAPIView.as_view(),
        name='assinaturabancoarquivo'
    ),
    path(
        'TipoPergSegur/',
        TipoPergSegurAPIView.as_view(),
        name='tipopergsegur'
    ),
    path(
        'Seguranca/',
        SegurancaAPIView.as_view(),
        name='seguranca'
    ),
    path(
        'BancoArquivoTraducao/',
        BancoArquivoTraducaoAPIView.as_view(),
        name='bancoarquivotraducao'
    ),
    path(
        'TipoListaContato/',
        TipoListaContatoAPIView.as_view(),
        name='tipolistacontato'
    ),
    path(
        'ItemPermissao/',
        ItemPermissaoAPIView.as_view(),
        name='itempermissao'
    ),
    path(
        'ParParteLinguaPais/',
        ParParteLinguaPaisAPIView.as_view(),
        name='parpartelinguapais'
    ),
    path(
        'TipoCalendLunar/',
        TipoCalendLunarAPIView.as_view(),
        name='tipocalendlunar'
    ),
    path(
        'RelDiagServAdLegendagem/',
        RelDiagServAdLegendagemAPIView.as_view(),
        name='reldiagservadlegendagem'
    ),
    path(
        'RelDiagServAdRedacao/',
        RelDiagServAdRedacaoAPIView.as_view(),
        name='reldiagservadredacao'
    ),
    path(
        'RelDiagServAdConsulLinguistica/',
        RelDiagServAdConsulLinguisticaAPIView.as_view(),
        name='reldiagservadconsullinguistica'
    ),
    path(
        'RelDiagServAdAuditLinguistica/',
        RelDiagServAdAuditLinguisticaAPIView.as_view(),
        name='reldiagservadauditlinguistica'
    ),
    path(
        'RelDiagServAdDublagem/',
        RelDiagServAdDublagemAPIView.as_view(),
        name='reldiagservaddublagem'
    ),
    path(
        'RelDiagServAdLocucao/',
        RelDiagServAdLocucaoAPIView.as_view(),
        name='reldiagservadlocucao'
    ),
    path(
        'CodigoPromocional/',
        CodigoPromocionalAPIView.as_view(),
        name='codigopromocional'
    ),
    path(
        'Plano/',
        PlanoAPIView.as_view(),
        name='plano'
    ),
    path(
        'Etapa/',
        EtapaAPIView.as_view(),
        name='etapa'
    ),
    path(
        'ExperienciaAdministratOutra/',
        ExperienciaAdministratOutraAPIView.as_view(),
        name='experienciaadministratoutra'
    ),
    path(
        'ExperienciaComercialOutra/',
        ExperienciaComercialOutraAPIView.as_view(),
        name='experienciacomercialoutra'
    ),
    path(
        'RelDiagServAdRevisaoTexto/',
        RelDiagServAdRevisaoTextoAPIView.as_view(),
        name='reldiagservadrevisaotexto'
    ),
    path(
        'RelDiagServAdDiagramacao/',
        RelDiagServAdDiagramacaoAPIView.as_view(),
        name='reldiagservaddiagramacao'
    ),
    path(
        'RelDiagServAdTranscricaoAudio/',
        RelDiagServAdTranscricaoAudioAPIView.as_view(),
        name='reldiagservadtranscricaoaudio'
    ),
    path(
        'RelDiagServAdAudiodescricao/',
        RelDiagServAdAudiodescricaoAPIView.as_view(),
        name='reldiagservadaudiodescricao'
    ),
    path(
        'DescricaoAdicional/',
        DescricaoAdicionalAPIView.as_view(),
        name='descricaoadicional'
    ),
    path(
        'PreferenciaAdicionalEmpresa/',
        PreferenciaAdicionalEmpresaAPIView.as_view(),
        name='preferenciaadicionalempresa'
    ),
    path(
        'EmpresaTraducao/',
        EmpresaTraducaoAPIView.as_view(),
        name='empresatraducao'
    ),
    path(
        'CodigoEndPostDesc/',
        CodigoEndPostDescAPIView.as_view(),
        name='codigoendpostdesc'
    ),
    path(
        'TipoFeriado/',
        TipoFeriadoAPIView.as_view(),
        name='tipoferiado'
    ),
    # path(
    #     'documento/pre/<str:Tipo>/<str:Titulo>/<str:Servico>/<str:Cargo>/<str:SubTipo>',
    #     views.geradorDocumento.as_view(),
    #     name='visualizadordeclausulas'
    # ),
    # path(
    #     'documento/download/<str:Contratante>/<str:Contratado>/<str:Tipo>/<str:Titulo>/<str:Servico>/<str:Cargo>/<str:SubTipo>',
    #     views.downloadDocumentos.as_view(),
    #     name='downloaddocumentos'
    # ),
    # path(
    #     'cadastro/<str:Tipo>/<int:idpedido>',
    #     views.salvamentoView.as_view(),
    #     name='salva'
    # ),
    # path(
    #     'ajax/pais/<str:Pais>',
    #     views.ajaxPais.as_view(),
    # ),
    # path(
    #     'ajax/lingua/<str:Lingua>',
    #     views.ajaxLingua.as_view(),
    # ),
    # path(
    #     'ajax/parte/<str:Parte>',
    #     views.ajaxParte.as_view(),
    # ),
    # path(
    #     'proposta',
    #     views.propostaView.as_view(),
    #     name = 'tela_proposta'
    # ),
    # path(
    #     'relatorio/<int:idpedido>/<str:relatorio_tipo>/',
    #     views.relatorioView.as_view(),
    #     name = 'relatorio'
    # ),
    # path(
    #     'ajax/validar/login/',
    #     views.ajaxLogin.as_view(),
    #     name = 'ajax_login'
    # ),
    # path(
    #     'ajax/validar/inscrevase/<str:tipo>',
    #     views.ajaxInscrevase.as_view(),
    #     name = 'ajax_inscrevase'
    # ),
    # path(
    #     'ajax/vazio/',
    #     views.ajaxVazio.as_view(),
    #     name = 'ajax_subimt_vazio'
    # ),
    # path(
    #     'clausulas/apagar',
    #     views.apagaDocumento.as_view(),
    # ),
    # path('lingua/pais', views.linghaPais.as_view()),
    # path('excel2', views.Ecxel2, name='Excel2'),
    # path('excel3', views.Ecxel3, name='Excel3'),
    # path('excel4', views.Ecxel4, name='Excel4'),
    # path('doc_in', views.BancoDocumentos, name='Doc_in'),
    # path('download', views.Download, name='Download'),
]
urlpatterns += staticfiles_urlpatterns()
